"""Aufbauschritt 3: die Prozessobjekte der Gruppe und ihre Ketten.

Ein Prozessobjekt beschreibt nach A.5 genau zehn Felder — nicht mehr. Die
Tiefe liegt im Graphen: die Frischedisposition ist fuer sich harmlos und wird
kritisch, weil der Bestellvorschlag an ihr haengt. Genau solche Ketten sind hier
angelegt, weil ohne sie die Cockpit-Zeile „Kritikalitaetsketten" leer bliebe
und die Vererbung aus A.4.2 nie sichtbar wuerde.

Die Bewertungen stehen in ``bewertungen.py``; hier entstehen nur die Objekte
und ihre Verknuepfungen.
"""

from __future__ import annotations

from dataclasses import dataclass, field

from app.bestand import organisation
from app.bestand.kontext import Kontext
from app.models.enums import Ausfallfolge as A
from app.models.enums import Kundenkreis as C
from app.schemas.prozess import ProzessAendern, ProzessAnlegen
from app.services import prozess as prozess_service


@dataclass(frozen=True)
class Prozess:
    """Ein Prozessobjekt im Katalog, mit allem, was A.5 dafuer verlangt."""

    schluessel: str
    name: str
    bereich: str
    owner: str
    vertretung: str
    supplier: str
    schritte: tuple[str, ...]
    output: str
    kunde: str
    ausfallfolge: str
    eingang: tuple[str, ...] = ()
    ergebnis: tuple[str, ...] = ()
    laender: tuple[str, ...] = ()
    nachgelagert: tuple[str, ...] = ()
    ziele: tuple[str, ...] = ()
    #: Wie viele Tage vor heute das Objekt angelegt wurde.
    angelegt_vor: int = 400
    #: Lokale Abweichungen der Umsetzung, je Landesgesellschaft. Sie schreibt
    #: der Prozess-Umsetzer des Landes — und nur er (Matrix 5.3).
    abweichungen: dict[str, str] = field(default_factory=dict)


PROZESSE: tuple[Prozess, ...] = (
    # --- Einkauf Food ------------------------------------------------------
    Prozess(
        "konditionsverhandlung",
        "Konditionsverhandlung Molkerei",
        "einkauf-food",
        "kuepper",
        "brandes",
        "Molkereilieferanten",
        (
            "Konditionsangebote einholen",
            "Angebote gegen Vorjahr rechnen",
            "Verhandlungsrunde führen",
            "Konditionen im System hinterlegen",
        ),
        "Verhandelte Jahreskonditionen",
        C.BEREICH,
        A.SPUERBAR,
        eingang=("lieferantenstamm", "einkaufskonditionen", "wettbewerbspreise"),
        ergebnis=("einkaufskonditionen",),
        laender=("einkauf-food-de", "einkauf-food-pl"),
        nachgelagert=("artikelanlage",),
        angelegt_vor=690,
    ),
    Prozess(
        "artikelanlage",
        "Artikelanlage und Listung",
        "einkauf-food",
        "brandes",
        "kuepper",
        "Category Management",
        (
            "Artikeldaten vom Lieferanten übernehmen",
            "Daten auf Vollständigkeit prüfen",
            "Artikel listen",
            "Filialsortimente zuordnen",
        ),
        "Gelisteter Artikel im Stammsatz",
        C.UNTERNEHMEN,
        A.KRITISCH,
        eingang=("lieferantenstamm", "artikelstamm-food"),
        ergebnis=("artikelstamm-food",),
        laender=("einkauf-food-de", "einkauf-food-pl", "einkauf-food-cz", "einkauf-food-ro"),
        angelegt_vor=685,
        abweichungen={
            "einkauf-food-pl": "Listung erst nach Freigabe durch das lokale Category Management.",
            "einkauf-food-ro": "Zusätzliche Prüfung der Etikettensprache vor der Listung.",
        },
    ),
    Prozess(
        "aktionsplanung",
        "Aktionsplanung Food",
        "einkauf-food",
        "kuepper",
        "brandes",
        "Category Management und Marketing",
        (
            "Aktionsrahmen festlegen",
            "Artikel und Mengen planen",
            "Aktionspreise kalkulieren",
            "Aktion freigeben",
        ),
        "Freigegebene Aktionsplanung",
        C.UNTERNEHMEN,
        A.SPUERBAR,
        eingang=("aktionsplanung-food", "abverkauf-filiale", "wettbewerbspreise"),
        ergebnis=("aktionsplanung-food",),
        laender=("einkauf-food-de", "einkauf-food-pl", "einkauf-food-cz"),
        angelegt_vor=640,
    ),
    Prozess(
        "eigenmarkenkalkulation",
        "Kalkulation Eigenmarken",
        "einkauf-food",
        "brandes",
        "kuepper",
        "Einkauf und Qualitätssicherung",
        (
            "Rezeptur- und Rohstoffkosten erfassen",
            "Deckungsbeitrag rechnen",
            "Verkaufspreis vorschlagen",
        ),
        "Kalkulierter Verkaufspreis",
        C.BEREICH,
        A.GERING,
        eingang=("eigenmarken-kalkulation", "einkaufskonditionen"),
        ergebnis=("eigenmarken-kalkulation",),
        angelegt_vor=600,
    ),
    Prozess(
        "lieferantenbewertung-food",
        "Lieferantenbewertung Food",
        "einkauf-food",
        "kuepper",
        "brandes",
        "Einkauf, Logistik und Qualitätssicherung",
        (
            "Kennzahlen je Lieferant zusammenführen",
            "Bewertung berechnen",
            "Ergebnis mit dem Lieferanten besprechen",
        ),
        "Lieferantenbewertung je Quartal",
        C.BEREICH,
        A.GERING,
        eingang=("lieferantenbewertung", "retourenmeldungen", "laborbefunde"),
        ergebnis=("lieferantenbewertung",),
        ziele=("edi.lieferantenportal.de",),
        angelegt_vor=520,
    ),
    Prozess(
        "persoenliche-artikelauswertung",
        "Persönliche Artikelauswertung",
        "einkauf-food",
        "kuepper",
        "brandes",
        "Warenwirtschaft",
        (
            "Artikel- und Abverkaufsdaten ziehen",
            "Eigene Sicht auf die Warengruppe bauen",
            "Auswertung für das Lieferantengespräch mitnehmen",
        ),
        "Eigene Warengruppenübersicht",
        # Der klassische Fall aus dem Citizen Development: gebaut fuer sich
        # selbst, von niemandem sonst benutzt. Reichweite „persoenlich".
        C.PERSOENLICH,
        A.KEINE,
        eingang=("artikelstamm-food", "abverkauf-filiale"),
        angelegt_vor=185,
    ),
    # --- Einkauf Nonfood ---------------------------------------------------
    Prozess(
        "saisonplanung",
        "Saisonplanung Nonfood",
        "einkauf-nonfood",
        "gruber",
        "ehlers",
        "Category Management Nonfood",
        (
            "Saisonthemen festlegen",
            "Mengen je Filialtyp planen",
            "Bestellungen auslösen",
            "Nachdisposition steuern",
        ),
        "Saisonmengenplan",
        C.UNTERNEHMEN,
        A.SPUERBAR,
        eingang=("mengenplanung-saison", "artikelstamm-nonfood"),
        ergebnis=("mengenplanung-saison",),
        laender=("einkauf-nonfood-de", "einkauf-nonfood-pl"),
        angelegt_vor=610,
        abweichungen={"einkauf-nonfood-pl": "Saisonstart zwei Wochen später als international."},
    ),
    Prozess(
        "gefahrstoffpruefung",
        "Gefahrstoffprüfung Nonfood",
        "einkauf-nonfood",
        "ehlers",
        "gruber",
        "Lieferanten und Qualitätssicherung",
        (
            "Sicherheitsdatenblätter anfordern",
            "Einstufung prüfen",
            "Kennzeichnung festlegen",
            "Kataster fortschreiben",
        ),
        "Geprüfte Gefahrstoffkennzeichnung",
        C.BEREICH,
        A.SPUERBAR,
        eingang=("gefahrstoffliste", "lieferantenaudits"),
        ergebnis=("gefahrstoffliste",),
        angelegt_vor=470,
    ),
    Prozess(
        "retourensteuerung-nonfood",
        "Retourensteuerung Nonfood",
        "einkauf-nonfood",
        "gruber",
        "ehlers",
        "Filialen und Zentrallager",
        (
            "Retourenmeldungen sammeln",
            "Quoten je Artikel auswerten",
            "Maßnahmen mit dem Lieferanten vereinbaren",
        ),
        "Retourenmaßnahmenliste",
        C.TEAM,
        A.GERING,
        eingang=("retourenquoten", "retourenmeldungen"),
        angelegt_vor=150,
    ),
    # --- Vertrieb und Filialbetrieb ---------------------------------------
    Prozess(
        "bestellvorschlag",
        "Bestellvorschlag Filiale",
        "vertrieb",
        "hofmann",
        "baumgart",
        "Warenwirtschaft und Filialen",
        (
            "Bestand und Abverkauf lesen",
            "Bedarfe je Artikel rechnen",
            "Vorschlag an die Filiale geben",
            "Bestellung übernehmen",
        ),
        "Bestellvorschlag je Filiale und Tag",
        C.UNTERNEHMEN,
        A.KRITISCH,
        eingang=("bestand-filiale", "abverkauf-filiale", "mhd-restlaufzeiten"),
        ergebnis=("bestand-filiale",),
        laender=(
            "vertrieb-de",
            "vertrieb-pl",
            "vertrieb-cz",
            "vertrieb-ro",
            "vertrieb-it",
            "vertrieb-es",
            "vertrieb-hr",
        ),
        nachgelagert=("nachschubsteuerung",),
        angelegt_vor=700,
        abweichungen={
            "vertrieb-it": "Bestellrhythmus zweimal täglich statt einmal, wegen kleinerer Flächen.",
            "vertrieb-hr": "Frischeartikel werden lokal disponiert, nicht über den Vorschlag.",
            "vertrieb-es": "Vorschlag wird vor der Übernahme durch die Filialleitung bestätigt.",
        },
    ),
    Prozess(
        "frischedisposition",
        "Frischedisposition",
        "vertrieb",
        "baumgart",
        "hofmann",
        "Filialen und Zentrallager",
        (
            "Reichweiten je Frischeartikel rechnen",
            "Abschriftenrisiko bewerten",
            "Dispositionsvorschlag erzeugen",
        ),
        "Dispositionsvorschlag Frische",
        C.BEREICH,
        A.SPUERBAR,
        eingang=("abverkauf-filiale", "mhd-restlaufzeiten", "abschriften"),
        ergebnis=("abschriften",),
        laender=("vertrieb-de", "vertrieb-pl"),
        nachgelagert=("bestellvorschlag",),
        angelegt_vor=660,
    ),
    Prozess(
        "abschriftensteuerung",
        "Abschriftensteuerung",
        "vertrieb",
        "baumgart",
        "hofmann",
        "Filialen",
        (
            "Abschriften je Filiale erfassen",
            "Auffälligkeiten markieren",
            "Rückmeldung an die Filialleitung",
        ),
        "Abschriftenbericht je Woche",
        C.TEAM,
        A.GERING,
        eingang=("abschriften", "bestand-filiale"),
        nachgelagert=("frischedisposition",),
        angelegt_vor=520,
    ),
    Prozess(
        "inventurabwicklung",
        "Inventurabwicklung",
        "vertrieb",
        "hofmann",
        "baumgart",
        "Filialen und Wirtschaftsprüfung",
        ("Inventurtermine planen", "Zählung durchführen", "Differenzen klären", "Ergebnis buchen"),
        "Bestätigtes Inventurergebnis",
        C.UNTERNEHMEN,
        A.SPUERBAR,
        eingang=("inventurdifferenzen", "bestand-filiale"),
        ergebnis=("inventurdifferenzen",),
        laender=("vertrieb-de", "vertrieb-pl", "vertrieb-cz"),
        angelegt_vor=630,
    ),
    Prozess(
        "kassenabschluss",
        "Kassenabschluss Filiale",
        "vertrieb",
        "baumgart",
        "hofmann",
        "Kassensystem",
        (
            "Kassen abschließen",
            "Bargeldbestand abgleichen",
            "Tagesumsatz melden",
            "Differenzen dokumentieren",
        ),
        "Gemeldeter Tagesumsatz",
        C.UNTERNEHMEN,
        A.KRITISCH,
        eingang=("kassenjournal",),
        ergebnis=("umsatzmeldung",),
        laender=("vertrieb-de", "vertrieb-pl", "vertrieb-cz", "vertrieb-ro"),
        angelegt_vor=695,
        abweichungen={
            "vertrieb-cz": "Tagesumsatz wird zusätzlich an die lokale Registrierkasse gemeldet.",
        },
    ),
    Prozess(
        "schwundanalyse",
        "Schwundanalyse",
        "vertrieb",
        "kortmann",
        "hofmann",
        "Filialen und Sicherheitstechnik",
        (
            "Schwund je Warengruppe auswerten",
            "Auffällige Filialen bestimmen",
            "Vor-Ort-Prüfung veranlassen",
        ),
        "Schwundbericht je Filiale",
        C.BEREICH,
        A.GERING,
        eingang=("schwundstatistik", "inventurdifferenzen", "videoaufzeichnungen"),
        angelegt_vor=450,
    ),
    Prozess(
        "regalpflege",
        "Regalpflege und Flächenkontrolle",
        "vertrieb",
        "deffner",
        "baumgart",
        "Filialen",
        ("Planogramm bereitstellen", "Umsetzung fotografieren", "Abweichungen zurückmelden"),
        "Flächenkontrollbericht",
        C.TEAM,
        A.GERING,
        eingang=("regalplanogramme", "filialfotos"),
        angelegt_vor=300,
    ),
    Prozess(
        "filialbesuche",
        "Filialbesuche der Regionalleitung",
        "vertrieb",
        "hofmann",
        "baumgart",
        "Regionalleitung",
        ("Besuch planen", "Checkliste vor Ort ausfüllen", "Bericht ablegen"),
        "Besuchsbericht",
        C.BEREICH,
        A.KEINE,
        eingang=("filialbesuchsberichte", "filialstammdaten"),
        angelegt_vor=560,
    ),
    Prozess(
        "preisauszeichnung",
        "Preisauszeichnung Filiale",
        "vertrieb",
        "baumgart",
        "hofmann",
        "Marketing und Warenwirtschaft",
        (
            "Preise aus der Aktionsplanung übernehmen",
            "Etiketten erzeugen",
            "Auszeichnung in der Filiale prüfen",
        ),
        "Ausgezeichneter Verkaufspreis",
        C.EXTERN,
        A.SPUERBAR,
        eingang=("handzettelpreise", "artikelstamm-food"),
        ergebnis=("handzettelpreise",),
        laender=("vertrieb-de", "vertrieb-cz"),
        angelegt_vor=575,
        abweichungen={"vertrieb-cz": "Preisschilder werden zweisprachig ausgegeben."},
    ),
    Prozess(
        "sortimentsveroeffentlichung",
        "Sortimentsveröffentlichung",
        "vertrieb",
        "hofmann",
        "baumgart",
        "Category Management",
        (
            "Sortiment je Filiale zusammenstellen",
            "Öffnungszeiten ergänzen",
            "Veröffentlichung freigeben",
        ),
        "Veröffentlichtes Filialsortiment",
        C.EXTERN,
        A.GERING,
        eingang=("sortimentsliste", "oeffnungszeiten"),
        ziele=("www.unternehmensauftritt.de",),
        angelegt_vor=380,
    ),
    # Der Bewertungsdurchlauf trifft hier den Verbotstatbestand aus Schritt 1b:
    # Emotionserkennung am Arbeitsplatz ist nach EU AI Act untersagt. Es
    # entsteht keine Bewertung, sondern ein Governance-Alarm.
    Prozess(
        "emotionsanalyse-kasse",
        "Stimmungsanalyse an der Kasse",
        "vertrieb",
        "baumgart",
        "hofmann",
        "Sicherheitstechnik und Kassensystem",
        (
            "Kamerabilder der Kassenzone auswerten",
            "Stimmungslage je Kasse ableiten",
            "Auffälligkeiten an die Filialleitung melden",
        ),
        "Stimmungsindex je Kassenplatz",
        C.BEREICH,
        A.GERING,
        eingang=("videoaufzeichnungen", "bondaten"),
        angelegt_vor=75,
    ),
    # --- Logistik ----------------------------------------------------------
    Prozess(
        "tourenoptimierung",
        "Tourenoptimierung Nachtsprung",
        "logistik",
        "arnold",
        "schaefer",
        "Transportdisposition",
        ("Sendungen bündeln", "Touren rechnen", "Fahrer zuordnen", "Tourenplan freigeben"),
        "Freigegebener Tourenplan",
        C.BEREICH,
        A.SPUERBAR,
        eingang=("tourenplanung", "rampenbelegung", "fahrerdisposition"),
        ergebnis=("tourenplanung",),
        laender=("logistik-de", "logistik-pl"),
        angelegt_vor=505,
        abweichungen={
            "logistik-de": "Nachtsprung nur für Filialen mit Nachtannahme, sonst morgens.",
        },
    ),
    Prozess(
        "wareneingang",
        "Wareneingang Zentrallager",
        "logistik",
        "schaefer",
        "arnold",
        "Lieferanten und Spediteure",
        ("Avis abgleichen", "Ware vereinnahmen", "Abweichungen erfassen", "Bestand buchen"),
        "Gebuchter Wareneingang",
        C.UNTERNEHMEN,
        A.KRITISCH,
        eingang=("wareneingangsavise", "lieferscheine"),
        ergebnis=("bestand-lager",),
        laender=("logistik-de", "logistik-pl", "logistik-cz"),
        angelegt_vor=680,
    ),
    Prozess(
        "nachschubsteuerung",
        "Nachschubsteuerung Filiale",
        "logistik",
        "schaefer",
        "arnold",
        "Zentrallager",
        ("Filialbedarf lesen", "Kommissionierung anstoßen", "Auslieferung bestätigen"),
        "Kommissionierter Filialnachschub",
        C.UNTERNEHMEN,
        A.SPUERBAR,
        eingang=("bestand-lager", "bestand-filiale"),
        ergebnis=("bestand-filiale",),
        laender=("logistik-de", "logistik-pl"),
        angelegt_vor=670,
    ),
    Prozess(
        "frachtkostenabrechnung",
        "Frachtkostenabrechnung",
        "logistik",
        "arnold",
        "schaefer",
        "Spediteure",
        ("Frachtbriefe zusammenführen", "Tarife prüfen", "Abrechnung freigeben"),
        "Freigegebene Frachtabrechnung",
        C.BEREICH,
        A.GERING,
        eingang=("frachtkosten", "lieferscheine"),
        ergebnis=("frachtkosten",),
        angelegt_vor=430,
    ),
    Prozess(
        "kuehlkettenueberwachung",
        "Kühlkettenüberwachung",
        "logistik",
        "schaefer",
        "arnold",
        "Telematik und Filialen",
        (
            "Temperaturwerte einlesen",
            "Grenzwerte prüfen",
            "Abweichung melden",
            "Maßnahme dokumentieren",
        ),
        "Lückenloser Temperaturnachweis",
        C.UNTERNEHMEN,
        A.KRITISCH,
        eingang=("temperaturprotokolle",),
        ergebnis=("temperaturprotokolle",),
        laender=("logistik-de", "logistik-pl", "logistik-cz", "logistik-ro"),
        angelegt_vor=615,
    ),
    Prozess(
        "zollabwicklung",
        "Zollabwicklung Import",
        "logistik",
        "arnold",
        "schaefer",
        "Importeure und Zollbehörden",
        ("Zolltarifnummern prüfen", "Anmeldung erstellen", "Bescheid ablegen"),
        "Zollanmeldung",
        C.UNTERNEHMEN,
        A.SPUERBAR,
        eingang=("zollunterlagen", "importkontingente"),
        ergebnis=("zollunterlagen",),
        ziele=("zollportal.bund.de",),
        angelegt_vor=540,
    ),
    # --- Personal ----------------------------------------------------------
    Prozess(
        "personaleinsatzplanung",
        "Personaleinsatzplanung Filiale",
        "personal",
        "niemeyer",
        "reinhardt",
        "Filialleitung",
        (
            "Bedarfsprognose lesen",
            "Verfügbarkeiten abgleichen",
            "Dienstplan erstellen",
            "Plan mit dem Betriebsrat abstimmen",
        ),
        "Veröffentlichter Dienstplan",
        C.BEREICH,
        A.SPUERBAR,
        eingang=("dienstplaene", "personalbedarfsprognose", "zeiterfassung"),
        ergebnis=("dienstplaene",),
        laender=("personal-de", "personal-pl"),
        angelegt_vor=590,
        abweichungen={
            "personal-pl": "Abstimmung mit der Gewerkschaft statt mit einem Betriebsrat.",
        },
    ),
    Prozess(
        "entgeltlauf",
        "Entgeltabrechnungslauf",
        "personal",
        "reinhardt",
        "niemeyer",
        "Zeitwirtschaft und Personalsystem",
        ("Zeitdaten übernehmen", "Abrechnung rechnen", "Ergebnis prüfen", "Zahlung anstoßen"),
        "Abgerechnetes Entgelt",
        C.UNTERNEHMEN,
        A.KRITISCH,
        eingang=("entgeltabrechnung", "arbeitszeitkonten", "personalstammdaten"),
        ergebnis=("entgeltabrechnung",),
        laender=("personal-de", "personal-pl", "personal-cz"),
        angelegt_vor=650,
    ),
    Prozess(
        "bewerbervorauswahl",
        "Bewerbervorauswahl",
        "personal",
        "niemeyer",
        "reinhardt",
        "Bewerbermanagement",
        (
            "Bewerbungen erfassen",
            "Anforderungsabgleich rechnen",
            "Vorschlagsliste erzeugen",
            "Auswahl durch die Fachabteilung",
        ),
        "Vorschlagsliste je Stelle",
        C.BEREICH,
        A.GERING,
        eingang=("bewerberdaten",),
        ergebnis=("bewerberdaten",),
        angelegt_vor=310,
    ),
    Prozess(
        "fehlzeitenauswertung",
        "Fehlzeitenauswertung",
        "personal",
        "reinhardt",
        "niemeyer",
        "Zeitwirtschaft",
        ("Fehlzeiten je Filiale auswerten", "Auffälligkeiten bestimmen", "Gespräch veranlassen"),
        "Fehlzeitenbericht",
        C.BEREICH,
        A.GERING,
        eingang=("fehlzeiten", "zeiterfassung"),
        angelegt_vor=420,
    ),
    Prozess(
        "schulungssteuerung",
        "Schulungssteuerung",
        "personal",
        "niemeyer",
        "reinhardt",
        "Lernplattform",
        ("Pflichtschulungen zuordnen", "Teilnahme nachhalten", "Nachweis ablegen"),
        "Schulungsnachweis je Beschäftigtem",
        C.TEAM,
        A.GERING,
        eingang=("schulungsnachweise",),
        ergebnis=("schulungsnachweise",),
        angelegt_vor=360,
    ),
    Prozess(
        "befragungsauswertung",
        "Auswertung Mitarbeiterbefragung",
        "personal",
        "reinhardt",
        "niemeyer",
        "Befragungsplattform",
        ("Rohdaten einlesen", "Auswertung je Einheit rechnen", "Ergebnis veröffentlichen"),
        "Befragungsbericht je Einheit",
        C.UNTERNEHMEN,
        A.KEINE,
        eingang=("mitarbeiterbefragung",),
        angelegt_vor=120,
    ),
    Prozess(
        "leistungsdialog",
        "Leistungsdialog Führungskräfte",
        "personal",
        "niemeyer",
        "reinhardt",
        "Personalsystem",
        ("Beurteilungen erfassen", "Kalibrierung durchführen", "Ergebnis im Gespräch besprechen"),
        "Dokumentierte Leistungsbeurteilung",
        C.BEREICH,
        A.KEINE,
        eingang=("leistungsbeurteilungen",),
        ergebnis=("leistungsbeurteilungen",),
        angelegt_vor=395,
    ),
    # --- Finanzen und Controlling -----------------------------------------
    Prozess(
        "monatsabschluss",
        "Monatsabschluss",
        "finanzen",
        "koehler",
        "baier",
        "Buchhaltung und Vertriebscontrolling",
        (
            "Abschlussbuchungen erfassen",
            "Abgrenzungen bilden",
            "Ergebnis konsolidieren",
            "Bericht freigeben",
        ),
        "Freigegebener Monatsabschluss",
        C.UNTERNEHMEN,
        A.KRITISCH,
        eingang=("umsatzmeldung", "kreditorenrechnungen", "kostenstellenplan"),
        ergebnis=("filialergebnisrechnung",),
        laender=("finanzen-de", "finanzen-pl", "finanzen-it"),
        angelegt_vor=705,
        abweichungen={
            "finanzen-it": "Zusätzliche Meldung an die lokale Steuerbehörde vor der Freigabe.",
        },
    ),
    Prozess(
        "kreditorenpruefung",
        "Kreditorenrechnungsprüfung",
        "finanzen",
        "baier",
        "koehler",
        "Lieferanten",
        ("Rechnung erfassen", "Gegen Lieferschein prüfen", "Freigabe einholen", "Buchung anstoßen"),
        "Freigegebene Kreditorenrechnung",
        C.BEREICH,
        A.SPUERBAR,
        eingang=("kreditorenrechnungen", "lieferscheine"),
        ergebnis=("kreditorenrechnungen",),
        angelegt_vor=660,
    ),
    Prozess(
        "budgetplanung-prozess",
        "Budgetplanung",
        "finanzen",
        "koehler",
        "baier",
        "Fachbereiche",
        (
            "Planungsprämissen festlegen",
            "Bereichsplanungen einsammeln",
            "Konsolidieren",
            "Budget verabschieden",
        ),
        "Verabschiedetes Jahresbudget",
        C.UNTERNEHMEN,
        A.SPUERBAR,
        eingang=("budgetplanung", "filialergebnisrechnung"),
        ergebnis=("budgetplanung",),
        angelegt_vor=480,
    ),
    Prozess(
        "filialergebnis",
        "Filialergebnisrechnung",
        "finanzen",
        "baier",
        "koehler",
        "Buchhaltung und Expansion",
        ("Erlöse und Kosten je Filiale zuordnen", "Ergebnis rechnen", "Bericht verteilen"),
        "Ergebnisrechnung je Filiale",
        C.BEREICH,
        A.SPUERBAR,
        eingang=("filialergebnisrechnung", "umsatzmeldung", "energieverbrauch"),
        nachgelagert=("monatsabschluss",),
        angelegt_vor=460,
    ),
    Prozess(
        "steuerkennzahlen-meldung",
        "Steuerliche Kennzahlenmeldung",
        "finanzen",
        "koehler",
        "baier",
        "Buchhaltung",
        ("Kennzahlen ermitteln", "Meldung erstellen", "Übermittlung protokollieren"),
        "Übermittelte Steuermeldung",
        C.EXTERN,
        A.SPUERBAR,
        eingang=("steuerkennzahlen",),
        ergebnis=("steuerkennzahlen",),
        ziele=("elster.finanzverwaltung.de",),
        angelegt_vor=500,
    ),
    Prozess(
        "anlagenzugaenge",
        "Anlagenzugänge erfassen",
        "finanzen",
        "baier",
        "koehler",
        "Expansion und Bauabteilung",
        ("Zugänge aus dem Bauprojekt übernehmen", "Anlagenklasse zuordnen", "Abschreibung starten"),
        "Aktivierte Anlage",
        C.BEREICH,
        A.GERING,
        eingang=("anlagenbuchhaltung", "baufortschritt"),
        ergebnis=("anlagenbuchhaltung",),
        angelegt_vor=340,
    ),
    # --- Expansion und Immobilien -----------------------------------------
    Prozess(
        "standortbewertung",
        "Standortbewertung Neubau",
        "expansion",
        "haas",
        "fricke",
        "Maklernetz und Marktforschung",
        (
            "Standortdaten erheben",
            "Umsatzpotenzial schätzen",
            "Wirtschaftlichkeit rechnen",
            "Standort zur Entscheidung vorlegen",
        ),
        "Standortbewertung je Objekt",
        C.UNTERNEHMEN,
        A.SPUERBAR,
        eingang=("standortdaten", "standortprognosen", "abverkauf-filiale"),
        ergebnis=("standortprognosen",),
        angelegt_vor=530,
        laender=("expansion-de", "expansion-ro"),
        abweichungen={
            "expansion-ro": "Kaufkraftdaten aus lokaler Erhebung statt aus dem Panel.",
        },
    ),
    Prozess(
        "mietvertragsverwaltung",
        "Mietvertragsverwaltung",
        "expansion",
        "fricke",
        "haas",
        "Vermieter",
        ("Vertragsdaten erfassen", "Fristen überwachen", "Anpassungen verhandeln"),
        "Aktueller Vertragsbestand",
        C.BEREICH,
        A.SPUERBAR,
        eingang=("mietvertraege", "standortdaten"),
        ergebnis=("mietvertraege",),
        angelegt_vor=490,
    ),
    Prozess(
        "bauprojektsteuerung",
        "Bauprojektsteuerung",
        "expansion",
        "haas",
        "fricke",
        "Generalunternehmer",
        ("Bautenstand erfassen", "Termine und Kosten abgleichen", "Abweichungen eskalieren"),
        "Projektstatusbericht",
        C.BEREICH,
        A.GERING,
        eingang=("baufortschritt",),
        ergebnis=("baufortschritt",),
        angelegt_vor=410,
    ),
    Prozess(
        "energiemonitoring",
        "Energiemonitoring Filialen",
        "expansion",
        "fricke",
        "haas",
        "Gebäudeleittechnik",
        (
            "Verbrauchswerte einlesen",
            "Auffälligkeiten je Filiale bestimmen",
            "Maßnahme vorschlagen",
        ),
        "Energiebericht je Filiale",
        C.BEREICH,
        A.GERING,
        eingang=("energieverbrauch", "sensordaten-kuehlung"),
        angelegt_vor=100,
    ),
    # --- Marketing und Kundenbindung --------------------------------------
    Prozess(
        "kundenkartenprogramm",
        "Kundenkartenprogramm",
        "marketing",
        "bergmann",
        "roth",
        "Kundinnen und Kunden",
        (
            "Karte ausgeben",
            "Umsätze zuordnen",
            "Vorteile abrechnen",
            "Auskunftsersuchen bearbeiten",
        ),
        "Geführtes Kundenkonto",
        C.EXTERN,
        A.SPUERBAR,
        eingang=("kundenkartendaten", "kaufhistorie"),
        ergebnis=("kaufhistorie",),
        laender=("marketing-de", "marketing-cz"),
        angelegt_vor=620,
        abweichungen={"marketing-cz": "Kartenantrag ausschließlich digital, kein Papierformular."},
    ),
    Prozess(
        "couponsteuerung",
        "Personalisierte Couponsteuerung",
        "marketing",
        "roth",
        "bergmann",
        "Kundenbindungssystem",
        ("Zielgruppen bilden", "Coupons zuordnen", "Ausspielung steuern", "Einlösung auswerten"),
        "Zugeteilte Coupons je Kunde",
        C.EXTERN,
        A.SPUERBAR,
        eingang=("kaufhistorie", "coupon-einloesungen", "warenkorbanalysen"),
        ergebnis=("coupon-einloesungen",),
        angelegt_vor=330,
    ),
    Prozess(
        "newsletterversand",
        "Newsletterversand",
        "marketing",
        "bergmann",
        "roth",
        "Marketing",
        ("Verteiler pflegen", "Inhalte zusammenstellen", "Versand auslösen"),
        "Versendeter Newsletter",
        C.EXTERN,
        A.GERING,
        eingang=("newsletter-verteiler", "handzettelpreise"),
        ziele=("versand.dienstleister.de",),
        angelegt_vor=440,
    ),
    Prozess(
        "werbemittelplanung-prozess",
        "Werbemittelplanung",
        "marketing",
        "roth",
        "bergmann",
        "Agenturen",
        ("Werbethemen festlegen", "Artikel zuordnen", "Druckunterlagen freigeben"),
        "Freigegebene Werbemittel",
        C.UNTERNEHMEN,
        A.GERING,
        eingang=("werbemittelplanung", "aktionsplanung-food"),
        ergebnis=("werbemittelplanung",),
        angelegt_vor=370,
    ),
    Prozess(
        "reklamationsbearbeitung",
        "Reklamationsbearbeitung",
        "marketing",
        "bergmann",
        "roth",
        "Servicecenter",
        ("Reklamation aufnehmen", "Sachverhalt klären", "Entscheidung mitteilen"),
        "Bearbeitete Reklamation",
        C.EXTERN,
        A.SPUERBAR,
        eingang=("reklamationen", "bondaten"),
        ergebnis=("reklamationen",),
        angelegt_vor=350,
    ),
    # --- Qualitätssicherung ------------------------------------------------
    Prozess(
        "eigenmarkenpruefung",
        "Eigenmarkenprüfung",
        "qs",
        "ziegler",
        "mertens",
        "Labore und Lieferanten",
        ("Probenplan festlegen", "Proben ziehen", "Befunde bewerten", "Freigabe erteilen"),
        "Freigegebene Eigenmarkencharge",
        C.UNTERNEHMEN,
        A.KRITISCH,
        eingang=("laborbefunde", "lieferantenzertifikate"),
        ergebnis=("laborbefunde",),
        laender=("qs-de", "qs-pl"),
        angelegt_vor=670,
        abweichungen={"qs-pl": "Probenzahl je Charge verdoppelt, solange der Lieferant neu ist."},
    ),
    Prozess(
        "rueckrufabwicklung",
        "Rückrufabwicklung",
        "qs",
        "mertens",
        "ziegler",
        "Behörden und Lieferanten",
        (
            "Meldung entgegennehmen",
            "Betroffene Chargen bestimmen",
            "Filialen sperren",
            "Behörde informieren",
        ),
        "Abgeschlossener Rückruf",
        C.EXTERN,
        A.KRITISCH,
        eingang=("rueckrufmeldungen", "artikelstamm-food"),
        ergebnis=("rueckrufmeldungen",),
        ziele=("meldeportal.lebensmittelwarnung.de",),
        angelegt_vor=645,
    ),
    Prozess(
        "hygienekontrolle",
        "Hygienekontrolle Filiale",
        "qs",
        "ziegler",
        "mertens",
        "Filialen",
        ("Kontrollplan verteilen", "Kontrolle durchführen", "Mängel nachverfolgen"),
        "Hygieneprotokoll je Filiale",
        C.BEREICH,
        A.SPUERBAR,
        eingang=("hygieneprotokolle", "temperaturprotokolle"),
        ergebnis=("hygieneprotokolle",),
        angelegt_vor=555,
    ),
    Prozess(
        "arbeitssicherheit",
        "Arbeitssicherheitsmeldungen",
        "qs",
        "mertens",
        "ziegler",
        "Filialen und Betriebsarzt",
        ("Unfall melden", "Ursache untersuchen", "Maßnahme festlegen", "Wirksamkeit prüfen"),
        "Dokumentierte Unfallmeldung",
        C.UNTERNEHMEN,
        A.SPUERBAR,
        eingang=("unfallmeldungen", "betriebsanweisungen"),
        ergebnis=("unfallmeldungen",),
        angelegt_vor=485,
    ),
    Prozess(
        "lieferantenaudit",
        "Lieferantenaudit",
        "qs",
        "ziegler",
        "mertens",
        "Lieferanten",
        (
            "Audit planen",
            "Audit vor Ort durchführen",
            "Feststellungen dokumentieren",
            "Nachverfolgung steuern",
        ),
        "Auditbericht je Lieferant",
        C.BEREICH,
        A.GERING,
        eingang=("lieferantenaudits", "auditfeststellungen", "lieferantenzertifikate"),
        angelegt_vor=290,
    ),
    # --- IT und Digitalisierung -------------------------------------------
    Prozess(
        "schnittstellenbetrieb",
        "Schnittstellenbetrieb Warenwirtschaft",
        "it",
        "neubauer",
        "hartwig",
        "Anwendungsbetrieb",
        ("Schnittstellen überwachen", "Störungen bearbeiten", "Wiederanlauf sicherstellen"),
        "Betriebsbereite Schnittstellen",
        C.UNTERNEHMEN,
        A.KRITISCH,
        eingang=("schnittstellenverzeichnis", "systemprotokolle"),
        angelegt_vor=710,
    ),
    Prozess(
        "berechtigungsreview",
        "Berechtigungsreview",
        "it",
        "neubauer",
        "hartwig",
        "Fachbereiche",
        (
            "Rollen je Nutzer auswerten",
            "Bestätigung einholen",
            "Entzug umsetzen",
            "Ergebnis dokumentieren",
        ),
        "Bestätigter Berechtigungsstand",
        C.UNTERNEHMEN,
        A.SPUERBAR,
        eingang=("berechtigungsrollen", "personalstammdaten"),
        ergebnis=("berechtigungsrollen",),
        angelegt_vor=580,
    ),
    Prozess(
        "datenplattform",
        "Bereitstellung Data Warehouse",
        "it",
        "neubauer",
        "hartwig",
        "Quellsysteme",
        ("Ladestrecken planen", "Daten laden", "Qualität prüfen", "Auswertungen bereitstellen"),
        "Bereitgestellte Auswertungsschicht",
        C.UNTERNEHMEN,
        A.SPUERBAR,
        eingang=("abverkauf-filiale", "bestand-filiale", "umsatzmeldung"),
        ergebnis=("warenkorbanalysen",),
        angelegt_vor=600,
    ),
)


def handelnder(kontext: Kontext, prozess: Prozess) -> str:
    """Wer diesen Prozess anlegt und pflegt.

    Der Owner, wenn er darf. Sonst seine Stellvertretung — genau der Fall, den
    die Cockpit-Zeile „Prozesse ohne tragenden Owner" spaeter findet: der
    eingetragene Verantwortliche ist einer, der gar nicht schreiben darf.
    """
    org_id = kontext.einheit(prozess.bereich).id
    for schluessel in (prozess.owner, prozess.vertretung):
        if prozess_service.darf_schreiben(kontext.db, kontext.wer(schluessel), org_id):
            return schluessel
    return "renner"


def baue(kontext: Kontext) -> None:
    """Legt die Prozessobjekte an und verknuepft anschliessend die Ketten."""
    db = kontext.db
    for eintrag in PROZESSE:
        akteur = handelnder(kontext, eintrag)
        with kontext.aktion(eintrag.angelegt_vor, stunde=8 + (eintrag.angelegt_vor % 8)):
            objekt = prozess_service.anlegen(
                db,
                kontext.wer(akteur),
                ProzessAnlegen(
                    name=eintrag.name,
                    owner_user_id=kontext.person(eintrag.owner).id,
                    stellvertretung_user_id=kontext.person(eintrag.vertretung).id,
                    prozessgeber_org_id=kontext.einheit(eintrag.bereich).id,
                    supplier=eintrag.supplier,
                    input_datenobjekt_ids=[kontext.datenobjekt(s).id for s in eintrag.eingang],
                    process_steps="\n".join(eintrag.schritte),
                    output=eintrag.output,
                    output_datenobjekt_ids=[kontext.datenobjekt(s).id for s in eintrag.ergebnis],
                    customer=eintrag.kunde,
                    ausfallfolge=eintrag.ausfallfolge,
                    umsetzung_land_org_ids=[kontext.einheit(s).id for s in eintrag.laender],
                    erlaubte_externe_ziele=list(eintrag.ziele),
                ),
            )
        kontext.prozesse[eintrag.schluessel] = objekt
        kontext.angelegt[f"p:{eintrag.schluessel}"] = eintrag.angelegt_vor

    # Die Ketten erst danach: sie zeigen auf Prozesse, die es beim Anlegen des
    # ersten Objekts noch nicht gab. Verknuepft wird an einem Tag, an dem beide
    # Seiten schon bestanden — sonst haette der Nachweis eine Kante zu einem
    # Objekt, das es damals nicht gab.
    je_schluessel = {p.schluessel: p for p in PROZESSE}
    for eintrag in PROZESSE:
        if not eintrag.nachgelagert:
            continue
        juengste = min(
            [eintrag.angelegt_vor] + [je_schluessel[s].angelegt_vor for s in eintrag.nachgelagert]
        )
        with kontext.aktion(max(20, juengste - 5), stunde=11):
            prozess_service.aendern(
                db,
                kontext.wer(handelnder(kontext, eintrag)),
                kontext.prozess(eintrag.schluessel),
                ProzessAendern(
                    nachgelagert_ids=[kontext.prozess(s).id for s in eintrag.nachgelagert]
                ),
            )

    for eintrag in PROZESSE:
        for land, text in eintrag.abweichungen.items():
            umsetzung = next(
                u
                for u in kontext.prozess(eintrag.schluessel).umsetzungen
                if u.land_org_id == kontext.einheit(land).id
            )
            with kontext.aktion(max(20, eintrag.angelegt_vor - 40), stunde=14):
                prozess_service.umsetzung_aendern(
                    db,
                    kontext.wer(organisation.umsetzer_fuer(land) or handelnder(kontext, eintrag)),
                    umsetzung,
                    text,
                )
