"""Aufbauschritt 4: die Tool-Objekte und was sie tatsaechlich tun.

Hier entsteht die Spannung, von der die ganze Anwendung lebt: neben jedem
erklaerten Rahmen steht eine Messung. Die meisten Werkzeuge halten ihn ein.
Einige nicht — und zwar auf jede Art, die A.13.2 kennt: ein Datenobjekt
ausserhalb der Positivliste, eine Datenkategorie ueber der Obergrenze, ein
externes Ziel, das kein Prozess erklaert hat, ein Schreibzugriff auf eine
Lesekante, eine geplante Ausfuehrung ohne Menschen dazwischen, eine Identitaet,
die zur Ausfuehrungsart nicht passt.

Dazu die vier Schicht-2-Verstoesse, die diese Anwendung ohne Meldung erkennt:
geteiltes Konto, hinterlegte Dauerzugangsdaten, erklaerte undeklarierte Quellen
und die Entscheidung ueber Personen ohne Menschen dazwischen.
"""

from __future__ import annotations

from dataclasses import dataclass

from app.bestand.kontext import Kontext
from app.models.enums import Ausfuehrungsidentitaet as I
from app.models.enums import ImportTyp
from app.models.enums import Lauftyp as L
from app.models.enums import Zugriffsart as Z
from app.schemas.integration import ImportAnfrage, ImportDatensatz
from app.services import asset
from app.sync.importer import importiere

#: Die unauffaellige Erklaerung nach A.6: keine Entscheidung ueber Personen,
#: ein Mensch zwischen Ergebnis und Wirkung, keine undeklarierten Quellen.
UNAUFFAELLIG = (False, True, False)


@dataclass(frozen=True)
class Werkzeug:
    """Ein Tool-Objekt im Katalog, samt dem, was an ihm gemessen wird."""

    schluessel: str
    name: str
    beschreibung: str
    technologie: str | None
    kategorie: str
    owner: str
    vertretung: str
    bereich: str
    lauftyp: str | None = None
    identitaet: str | None = None
    statisch: bool | None = False
    prozesse: tuple[str, ...] = ()
    #: Datenobjekt und Zugriffsart — die gemessene Seite des Rahmens.
    daten: tuple[tuple[str, str], ...] = ()
    ziele: tuple[str, ...] = ()
    #: Die drei Erklaerungen nach A.6; ``None`` heisst: nie erklaert.
    attest: tuple[bool, bool, bool] | None = UNAUFFAELLIG
    angelegt_vor: int = 300
    attestiert_vor: int = 280
    letzte_aktivitaet_vor: int = 4
    stillgelegt: bool = False


WERKZEUGE: tuple[Werkzeug, ...] = (
    # --- Einkauf Food ------------------------------------------------------
    Werkzeug(
        "konditionsmappe",
        "Konditionsvergleich Molkerei",
        "Stellt Angebote der Molkereilieferanten dem Vorjahr gegenüber.",
        "apps-script",
        "Kalkulation",
        "oswald",
        "brandes",
        "einkauf-food",
        L.INTERAKTIV,
        I.PERSOENLICH,
        False,
        prozesse=("konditionsverhandlung",),
        daten=(
            ("einkaufskonditionen", Z.LESEN),
            ("wettbewerbspreise", Z.LESEN),
            ("lieferantenstamm", Z.LESEN),
        ),
        angelegt_vor=670,
        attestiert_vor=120,
    ),
    Werkzeug(
        "artikelanlage-import",
        "Artikelanlage Massenimport",
        "Übernimmt Artikeldaten der Lieferanten in den Stammsatz.",
        "python-kubernetes",
        "Ladestrecke",
        "oswald",
        "brandes",
        "einkauf-food",
        L.GEPLANT,
        I.BENANNTER_DIENST,
        False,
        prozesse=("artikelanlage",),
        daten=(("artikelstamm-food", Z.LESEN_SCHREIBEN), ("lieferantenstamm", Z.LESEN)),
        angelegt_vor=660,
        attestiert_vor=95,
    ),
    Werkzeug(
        "aktionscockpit",
        "Aktionscockpit Food",
        "Wertet Aktionen gegen Plan und Vorjahr aus.",
        "bigquery-gcs",
        "Auswertung",
        "oswald",
        "brandes",
        "einkauf-food",
        L.GETRIGGERT,
        I.BENANNTER_DIENST,
        False,
        prozesse=("aktionsplanung",),
        daten=(
            ("aktionsplanung-food", Z.LESEN_SCHREIBEN),
            ("abverkauf-filiale", Z.LESEN),
            ("wettbewerbspreise", Z.LESEN),
        ),
        angelegt_vor=615,
        attestiert_vor=88,
    ),
    Werkzeug(
        "kalkulationsmappe-eigenmarke",
        "Kalkulationsmappe Eigenmarken",
        "Rechnet Rohstoff- und Herstellkosten auf einen Verkaufspreis hoch.",
        "apps-script",
        "Kalkulation",
        "oswald",
        "brandes",
        "einkauf-food",
        L.INTERAKTIV,
        I.PERSOENLICH,
        False,
        prozesse=("eigenmarkenkalkulation",),
        daten=(("eigenmarken-kalkulation", Z.LESEN_SCHREIBEN), ("einkaufskonditionen", Z.LESEN)),
        angelegt_vor=580,
        attestiert_vor=150,
    ),
    Werkzeug(
        "lieferantenscorecard",
        "Lieferanten-Scorecard",
        "Führt Liefertreue, Retouren und Laborbefunde zu einer Bewertung zusammen.",
        "bigquery-gcs",
        "Auswertung",
        "oswald",
        "brandes",
        "einkauf-food",
        L.GEPLANT,
        I.BENANNTER_DIENST,
        False,
        prozesse=("lieferantenbewertung-food",),
        daten=(
            ("lieferantenbewertung", Z.LESEN_SCHREIBEN),
            ("retourenmeldungen", Z.LESEN),
            ("laborbefunde", Z.LESEN),
        ),
        ziele=("edi.lieferantenportal.de",),
        angelegt_vor=500,
        attestiert_vor=70,
    ),
    Werkzeug(
        "konditionsexport-portal",
        "Konditionsexport Lieferantenportal",
        "Stellt verhandelte Konditionen im Lieferantenportal bereit.",
        "apps-script",
        "Schnittstelle",
        "oswald",
        "brandes",
        "einkauf-food",
        L.GETRIGGERT,
        I.GETEILTES_KONTO,
        False,
        prozesse=("konditionsverhandlung",),
        daten=(("einkaufskonditionen", Z.LESEN),),
        ziele=("edi.lieferantenportal.de",),
        angelegt_vor=330,
        attestiert_vor=210,
    ),
    Werkzeug(
        "artikelauswertung-mappe",
        "Artikelauswertung Warengruppe",
        "Eigene Sicht auf Artikel und Abverkauf einer Warengruppe.",
        "apps-script",
        "Auswertung",
        "oswald",
        "brandes",
        "einkauf-food",
        L.INTERAKTIV,
        I.PERSOENLICH,
        False,
        prozesse=("persoenliche-artikelauswertung",),
        daten=(("artikelstamm-food", Z.LESEN), ("abverkauf-filiale", Z.LESEN)),
        # Erklaerte undeklarierte Quellen: Schicht 2, und dieser Fall bleibt
        # stehen. Der zweite Fall derselben Art (budgetkonsolidierung) wird
        # angepasst — ein Bestand braucht beides, sonst zeigt er entweder nur
        # geloeste oder nur offene Verstoesse.
        attest=(False, True, True),
        angelegt_vor=175,
        attestiert_vor=168,
        letzte_aktivitaet_vor=6,
    ),
    # --- Einkauf Nonfood ---------------------------------------------------
    Werkzeug(
        "saisonplanungsmappe",
        "Saisonplanung Mengengerüst",
        "Plant Saisonmengen je Filialtyp.",
        "apps-script",
        "Kalkulation",
        "vogler",
        "gruber",
        "einkauf-nonfood",
        L.INTERAKTIV,
        I.PERSOENLICH,
        False,
        prozesse=("saisonplanung",),
        daten=(("mengenplanung-saison", Z.LESEN_SCHREIBEN), ("artikelstamm-nonfood", Z.LESEN)),
        angelegt_vor=595,
        attestiert_vor=140,
    ),
    Werkzeug(
        "gefahrstoffkataster-app",
        "Gefahrstoffkataster",
        "Erfasst Einstufung und Kennzeichnung je Artikel.",
        "appsheet",
        "Erfassung",
        "vogler",
        "gruber",
        "einkauf-nonfood",
        L.INTERAKTIV,
        I.PERSOENLICH,
        False,
        prozesse=("gefahrstoffpruefung",),
        daten=(("gefahrstoffliste", Z.LESEN_SCHREIBEN), ("lieferantenaudits", Z.LESEN)),
        angelegt_vor=455,
        attestiert_vor=110,
    ),
    Werkzeug(
        "retourenauswertung",
        "Retourenauswertung Nonfood",
        "Wertet Retourenquoten je Artikel und Lieferant aus.",
        "bigquery-gcs",
        "Auswertung",
        "vogler",
        "gruber",
        "einkauf-nonfood",
        L.GEPLANT,
        I.BENANNTER_DIENST,
        False,
        prozesse=("retourensteuerung-nonfood",),
        daten=(("retourenquoten", Z.LESEN), ("retourenmeldungen", Z.LESEN)),
        angelegt_vor=140,
        attestiert_vor=135,
    ),
    # --- Vertrieb und Filialbetrieb ---------------------------------------
    Werkzeug(
        "bestellvorschlagsrechner",
        "Bestellvorschlagsrechner",
        "Rechnet täglich den Filialbedarf je Artikel.",
        "python-kubernetes",
        "Steuerung",
        "seidel",
        "lenz",
        "vertrieb",
        L.GEPLANT,
        I.BENANNTER_DIENST,
        False,
        prozesse=("bestellvorschlag",),
        daten=(
            ("bestand-filiale", Z.LESEN_SCHREIBEN),
            ("abverkauf-filiale", Z.LESEN),
            ("mhd-restlaufzeiten", Z.LESEN),
        ),
        angelegt_vor=690,
        attestiert_vor=60,
    ),
    Werkzeug(
        "frischeprognose",
        "Frischeprognose",
        "Schätzt Reichweiten und Abschriftenrisiko je Frischeartikel.",
        "bigquery-gcs",
        "Auswertung",
        "seidel",
        "lenz",
        "vertrieb",
        L.GEPLANT,
        I.BENANNTER_DIENST,
        False,
        prozesse=("frischedisposition",),
        # „kaufhistorie" haengt an keinem der Prozesse dieses Tools und traegt
        # eine hoehere Kategorie als der Rahmen deckt — zwei Abweichungen aus
        # einer einzigen Kante.
        daten=(
            ("abverkauf-filiale", Z.LESEN),
            ("abschriften", Z.LESEN_SCHREIBEN),
            ("mhd-restlaufzeiten", Z.LESEN),
            ("kaufhistorie", Z.LESEN),
        ),
        angelegt_vor=640,
        attestiert_vor=75,
    ),
    Werkzeug(
        "abschriftenmonitor",
        "Abschriftenmonitor",
        "Meldet auffällige Abschriften je Filiale und Warengruppe.",
        "apps-script",
        "Auswertung",
        "seidel",
        "lenz",
        "vertrieb",
        # Geplant, aber unter persoenlicher Identitaet: Element 7 des Rahmens.
        L.GEPLANT,
        I.PERSOENLICH,
        False,
        prozesse=("abschriftensteuerung",),
        daten=(("abschriften", Z.LESEN), ("bestand-filiale", Z.LESEN)),
        angelegt_vor=505,
        attestiert_vor=190,
    ),
    Werkzeug(
        "inventurauswertung",
        "Inventurauswertung",
        "Stellt Differenzen je Filiale und Warengruppe gegenüber.",
        "bigquery-gcs",
        "Auswertung",
        "lenz",
        "seidel",
        "vertrieb",
        L.GETRIGGERT,
        I.BENANNTER_DIENST,
        False,
        prozesse=("inventurabwicklung",),
        daten=(("inventurdifferenzen", Z.LESEN_SCHREIBEN), ("bestand-filiale", Z.LESEN)),
        angelegt_vor=600,
        attestiert_vor=52,
    ),
    Werkzeug(
        "kassenabschluss-melder",
        "Kassenabschluss-Meldung",
        "Übergibt den Tagesumsatz aus dem Kassensystem an die Buchhaltung.",
        "python-kubernetes",
        "Schnittstelle",
        "lenz",
        "seidel",
        "vertrieb",
        L.GEPLANT,
        I.BENANNTER_DIENST,
        False,
        prozesse=("kassenabschluss",),
        # Reiner Schreibzugriff: der Dienst legt die Tagesmeldung ab und liest
        # sie nie wieder.
        daten=(("kassenjournal", Z.LESEN), ("umsatzmeldung", Z.SCHREIBEN)),
        angelegt_vor=680,
        attestiert_vor=45,
    ),
    Werkzeug(
        "schwundcockpit",
        "Schwundcockpit",
        "Führt Schwund, Inventurdifferenzen und Kamerahinweise zusammen.",
        "bigquery-gcs",
        "Auswertung",
        "seidel",
        "lenz",
        "vertrieb",
        L.INTERAKTIV,
        I.PERSOENLICH,
        False,
        prozesse=("schwundanalyse",),
        daten=(
            ("schwundstatistik", Z.LESEN),
            ("inventurdifferenzen", Z.LESEN),
            ("videoaufzeichnungen", Z.LESEN),
        ),
        # Entscheidung ueber Personen, ohne Menschen dazwischen: Schicht 2.
        attest=(True, False, False),
        angelegt_vor=430,
        attestiert_vor=200,
    ),
    Werkzeug(
        "regalpflege-app",
        "Regalpflege-App",
        "Erfasst die Umsetzung der Planogramme in der Fläche.",
        "appsheet",
        "Erfassung",
        "seidel",
        "lenz",
        "vertrieb",
        L.INTERAKTIV,
        I.PERSOENLICH,
        False,
        prozesse=("regalpflege",),
        daten=(("regalplanogramme", Z.LESEN), ("filialfotos", Z.LESEN_SCHREIBEN)),
        angelegt_vor=285,
        attestiert_vor=280,
    ),
    Werkzeug(
        "filialbesuchsbogen",
        "Filialbesuchsbogen",
        "Checkliste der Regionalleitung für den Besuch vor Ort.",
        "appsheet",
        "Formular",
        "lenz",
        "seidel",
        "vertrieb",
        L.INTERAKTIV,
        I.PERSOENLICH,
        False,
        prozesse=("filialbesuche",),
        daten=(("filialbesuchsberichte", Z.LESEN_SCHREIBEN), ("filialstammdaten", Z.LESEN)),
        angelegt_vor=540,
        attestiert_vor=170,
    ),
    Werkzeug(
        "preisetiketten-erzeugung",
        "Preisetiketten-Erzeugung",
        "Erzeugt Etikettendateien aus der freigegebenen Preisliste.",
        "apps-script",
        "Ladestrecke",
        "lenz",
        "seidel",
        "vertrieb",
        L.GETRIGGERT,
        I.BENANNTER_DIENST,
        False,
        prozesse=("preisauszeichnung",),
        daten=(("handzettelpreise", Z.LESEN_SCHREIBEN), ("artikelstamm-food", Z.LESEN)),
        angelegt_vor=555,
        attestiert_vor=130,
    ),
    Werkzeug(
        "sortimentsexport-web",
        "Sortimentsexport Webauftritt",
        "Stellt Sortiment und Öffnungszeiten für den Webauftritt bereit.",
        "python-kubernetes",
        "Schnittstelle",
        "seidel",
        "lenz",
        "vertrieb",
        L.GEPLANT,
        I.BENANNTER_DIENST,
        False,
        prozesse=("sortimentsveroeffentlichung",),
        daten=(("sortimentsliste", Z.LESEN), ("oeffnungszeiten", Z.LESEN)),
        ziele=("www.unternehmensauftritt.de",),
        angelegt_vor=360,
        attestiert_vor=90,
    ),
    Werkzeug(
        "filialkennzahlen-tafel",
        "Filialkennzahlen-Tafel",
        "Kennzahlentafel für Filial- und Regionalleitung.",
        "bigquery-gcs",
        "Auswertung",
        "seidel",
        "lenz",
        "vertrieb",
        L.GETRIGGERT,
        I.BENANNTER_DIENST,
        False,
        # Zwei Prozesskanten: das Tool erbt das Maximum aus beiden (A.4.4).
        prozesse=("bestellvorschlag", "inventurabwicklung"),
        # Schreibend auf eine reine Lesekante — Element 5 des Rahmens.
        daten=(
            ("abverkauf-filiale", Z.LESEN_SCHREIBEN),
            ("bestand-filiale", Z.LESEN),
            ("inventurdifferenzen", Z.LESEN),
        ),
        angelegt_vor=470,
        attestiert_vor=64,
    ),
    Werkzeug(
        "frischeverlust-mappe",
        "Frischeverlustmappe",
        "Ältere Auswertung der Frischeverluste je Filiale.",
        "apps-script",
        "Auswertung",
        "lenz",
        "seidel",
        "vertrieb",
        L.INTERAKTIV,
        I.PERSOENLICH,
        False,
        prozesse=("frischedisposition",),
        daten=(("abschriften", Z.LESEN),),
        angelegt_vor=520,
        attestiert_vor=260,
        letzte_aktivitaet_vor=265,
    ),
    Werkzeug(
        "preisliste-versand",
        "Preislistenversand Filialen",
        "Verteilt die freigegebene Preisliste an die Filialen.",
        "apps-script",
        "Ladestrecke",
        "lenz",
        "seidel",
        "vertrieb",
        L.GETRIGGERT,
        I.BENANNTER_DIENST,
        False,
        prozesse=("preisauszeichnung",),
        daten=(("handzettelpreise", Z.LESEN),),
        angelegt_vor=560,
        attestiert_vor=500,
    ),
    Werkzeug(
        "altbestandsauswertung",
        "Bestandsauswertung (stillgelegt)",
        "Vorgängerlösung der Bestandsauswertung, seit der Ablösung außer Betrieb.",
        "apps-script",
        "Auswertung",
        "seidel",
        "lenz",
        "vertrieb",
        L.INTERAKTIV,
        I.PERSOENLICH,
        False,
        angelegt_vor=650,
        attestiert_vor=430,
        letzte_aktivitaet_vor=380,
        stillgelegt=True,
    ),
    Werkzeug(
        "mengenplanung-rohentwurf",
        "Mengenplanung Rohentwurf",
        "Entwurf einer Mengenplanung, noch ohne Prozesszuordnung.",
        None,
        "Kalkulation",
        "seidel",
        "lenz",
        "vertrieb",
        None,
        None,
        None,
        attest=None,
        angelegt_vor=45,
        letzte_aktivitaet_vor=12,
    ),
    Werkzeug(
        "mhd-auswertung",
        "MHD-Auswertung Frische",
        "Wertet Restlaufzeiten je Filiale und Warengruppe aus.",
        # Ohne Technologieangabe: die Matrix kennt dazu kein Feld, und eine
        # fehlende Angabe ist kein Nachweis — der Befund heisst „ungeprueft".
        None,
        "Auswertung",
        "seidel",
        "lenz",
        "vertrieb",
        L.INTERAKTIV,
        I.PERSOENLICH,
        False,
        prozesse=("frischedisposition",),
        daten=(("mhd-restlaufzeiten", Z.LESEN),),
        angelegt_vor=205,
        attestiert_vor=198,
        letzte_aktivitaet_vor=9,
    ),
    # --- Logistik ----------------------------------------------------------
    Werkzeug(
        "tourenrechner",
        "Tourenrechner Nachtsprung",
        "Bündelt Sendungen und rechnet Touren für den Nachtsprung.",
        "python-kubernetes",
        "Steuerung",
        "pohl",
        "schaefer",
        "logistik",
        L.GEPLANT,
        I.BENANNTER_DIENST,
        False,
        prozesse=("tourenoptimierung",),
        daten=(
            ("tourenplanung", Z.LESEN_SCHREIBEN),
            ("rampenbelegung", Z.LESEN),
            ("fahrerdisposition", Z.LESEN),
        ),
        angelegt_vor=495,
        attestiert_vor=58,
    ),
    Werkzeug(
        "wareneingangs-scanner",
        "Wareneingangs-Scanner",
        "Vereinnahmt Ware im Zentrallager gegen das Avis.",
        "appsheet",
        "Erfassung",
        "pohl",
        "schaefer",
        "logistik",
        L.INTERAKTIV,
        I.PERSOENLICH,
        False,
        prozesse=("wareneingang",),
        daten=(
            ("wareneingangsavise", Z.LESEN),
            ("bestand-lager", Z.LESEN_SCHREIBEN),
            ("lieferscheine", Z.LESEN),
        ),
        angelegt_vor=665,
        attestiert_vor=41,
    ),
    Werkzeug(
        "nachschubmonitor",
        "Nachschubmonitor",
        "Zeigt offene Filialbedarfe und den Kommissionierfortschritt.",
        "bigquery-gcs",
        "Auswertung",
        "pohl",
        "schaefer",
        "logistik",
        L.GEPLANT,
        I.BENANNTER_DIENST,
        False,
        prozesse=("nachschubsteuerung",),
        daten=(("bestand-lager", Z.LESEN), ("bestand-filiale", Z.LESEN)),
        angelegt_vor=655,
        attestiert_vor=100,
    ),
    Werkzeug(
        "bestandskorrektur-automat",
        "Bestandskorrektur-Automat",
        "Korrigiert Buchbestände im Lager ohne weitere Freigabe.",
        "python-kubernetes",
        "Steuerung",
        "pohl",
        "schaefer",
        "logistik",
        # Geplanter Lauf, obwohl kein Mensch zwischen Ergebnis und Wirkung
        # steht: der Rahmen erlaubt dann nur die interaktive Ausfuehrung.
        L.GEPLANT,
        I.BENANNTER_DIENST,
        False,
        prozesse=("nachschubsteuerung",),
        daten=(("bestand-lager", Z.LESEN_SCHREIBEN),),
        attest=(False, False, False),
        angelegt_vor=250,
        attestiert_vor=240,
    ),
    Werkzeug(
        "frachtabrechnungsmappe",
        "Frachtabrechnungsmappe",
        "Prüft Frachtabrechnungen gegen die vereinbarten Tarife.",
        "apps-script",
        "Kalkulation",
        "pohl",
        "schaefer",
        "logistik",
        L.INTERAKTIV,
        I.PERSOENLICH,
        False,
        prozesse=("frachtkostenabrechnung",),
        daten=(("frachtkosten", Z.LESEN_SCHREIBEN), ("lieferscheine", Z.LESEN)),
        angelegt_vor=420,
        attestiert_vor=160,
    ),
    Werkzeug(
        "kuehlkettenwaechter",
        "Kühlkettenwächter",
        "Prüft Temperaturwerte gegen die Grenzwerte und meldet Abweichungen.",
        "python-kubernetes",
        "Steuerung",
        "pohl",
        "schaefer",
        "logistik",
        L.GEPLANT,
        I.BENANNTER_DIENST,
        False,
        prozesse=("kuehlkettenueberwachung",),
        daten=(("temperaturprotokolle", Z.LESEN_SCHREIBEN),),
        angelegt_vor=605,
        attestiert_vor=35,
    ),
    Werkzeug(
        "zollanmeldung-uebertrag",
        "Zollanmeldung Übertragung",
        "Übermittelt Zollanmeldungen an das Portal der Zollverwaltung.",
        "python-kubernetes",
        "Schnittstelle",
        "pohl",
        "schaefer",
        "logistik",
        # Dauerhaft hinterlegte Zugangsdaten: Schicht 2, ohne erste Stufe.
        L.GETRIGGERT,
        I.BENANNTER_DIENST,
        True,
        prozesse=("zollabwicklung",),
        daten=(("zollunterlagen", Z.LESEN_SCHREIBEN), ("importkontingente", Z.LESEN)),
        ziele=("zollportal.bund.de",),
        angelegt_vor=520,
        attestiert_vor=175,
    ),
    Werkzeug(
        "lagerauswertung-pl",
        "Lagerauswertung Polen",
        "Lokale Auswertung der Lagerbewegungen in Polen.",
        "apps-script",
        "Auswertung",
        "wieczorek",
        "pohl",
        "logistik-pl",
        # Ein von mehreren genutztes Sammelkonto: Schicht 2.
        L.INTERAKTIV,
        I.GETEILTES_KONTO,
        False,
        prozesse=("wareneingang",),
        daten=(("bestand-lager", Z.LESEN), ("wareneingangsavise", Z.LESEN)),
        angelegt_vor=310,
        attestiert_vor=220,
    ),
    # --- Personal ----------------------------------------------------------
    Werkzeug(
        "dienstplanrechner",
        "Dienstplanrechner",
        "Erzeugt Dienstplanvorschläge aus Bedarf und Verfügbarkeit.",
        "python-kubernetes",
        "Steuerung",
        "albrecht",
        "kraus",
        "personal",
        L.GEPLANT,
        I.BENANNTER_DIENST,
        False,
        prozesse=("personaleinsatzplanung",),
        daten=(
            ("dienstplaene", Z.LESEN_SCHREIBEN),
            ("personalbedarfsprognose", Z.LESEN),
            ("zeiterfassung", Z.LESEN),
        ),
        angelegt_vor=575,
        attestiert_vor=48,
    ),
    Werkzeug(
        "entgeltvorbereitung",
        "Entgeltvorbereitung",
        "Bereitet Zeit- und Stammdaten für den Abrechnungslauf auf.",
        "python-kubernetes",
        "Ladestrecke",
        "kraus",
        "albrecht",
        "personal",
        L.GEPLANT,
        I.BENANNTER_DIENST,
        False,
        prozesse=("entgeltlauf",),
        daten=(
            ("entgeltabrechnung", Z.LESEN_SCHREIBEN),
            ("arbeitszeitkonten", Z.LESEN),
            ("personalstammdaten", Z.LESEN),
        ),
        angelegt_vor=635,
        attestiert_vor=30,
    ),
    Werkzeug(
        "bewerbermatching",
        "Bewerbermatching",
        "Gleicht Bewerbungen mit dem Anforderungsprofil der Stelle ab.",
        "python-kubernetes",
        "Steuerung",
        "albrecht",
        "kraus",
        "personal",
        L.GETRIGGERT,
        I.BENANNTER_DIENST,
        False,
        prozesse=("bewerbervorauswahl",),
        daten=(("bewerberdaten", Z.LESEN_SCHREIBEN),),
        # Das Ergebnis fliesst in eine Entscheidung ueber Personen — aber ein
        # Mensch entscheidet. Kein Verstoss, wohl aber Mitbestimmung.
        attest=(True, True, False),
        angelegt_vor=300,
        attestiert_vor=290,
    ),
    Werkzeug(
        "fehlzeitenreport",
        "Fehlzeitenreport",
        "Wertet Fehlzeiten je Filiale und Zeitraum aus.",
        "bigquery-gcs",
        "Auswertung",
        "kraus",
        "albrecht",
        "personal",
        L.GEPLANT,
        I.BENANNTER_DIENST,
        False,
        prozesse=("fehlzeitenauswertung",),
        daten=(("fehlzeiten", Z.LESEN), ("zeiterfassung", Z.LESEN)),
        angelegt_vor=405,
        attestiert_vor=180,
    ),
    Werkzeug(
        "schulungsnachweis-app",
        "Schulungsnachweis-App",
        "Erfasst Teilnahme und Nachweis der Pflichtschulungen.",
        "appsheet",
        "Erfassung",
        "albrecht",
        "kraus",
        "personal",
        L.INTERAKTIV,
        I.PERSOENLICH,
        False,
        prozesse=("schulungssteuerung",),
        daten=(("schulungsnachweise", Z.LESEN_SCHREIBEN),),
        angelegt_vor=345,
        attestiert_vor=155,
    ),
    Werkzeug(
        "befragungsauswertung-mappe",
        "Auswertungsmappe Befragung",
        "Wertet die Mitarbeiterbefragung je Einheit aus.",
        "apps-script",
        "Auswertung",
        "kraus",
        "albrecht",
        "personal",
        L.INTERAKTIV,
        I.PERSOENLICH,
        False,
        prozesse=("befragungsauswertung",),
        daten=(("mitarbeiterbefragung", Z.LESEN),),
        angelegt_vor=110,
        attestiert_vor=105,
    ),
    Werkzeug(
        "leistungsdialog-mappe",
        "Leistungsdialog-Mappe",
        "Führt Beurteilungen für die Kalibrierungsrunde zusammen.",
        "apps-script",
        "Erfassung",
        "albrecht",
        "kraus",
        "personal",
        L.INTERAKTIV,
        I.PERSOENLICH,
        False,
        prozesse=("leistungsdialog",),
        daten=(("leistungsbeurteilungen", Z.LESEN_SCHREIBEN),),
        angelegt_vor=380,
        attestiert_vor=185,
    ),
    # --- Finanzen und Controlling -----------------------------------------
    Werkzeug(
        "abschlusscockpit",
        "Abschlusscockpit",
        "Zeigt den Stand der Abschlussarbeiten je Gesellschaft.",
        "bigquery-gcs",
        "Auswertung",
        "steiner",
        "winkler",
        "finanzen",
        L.GETRIGGERT,
        I.BENANNTER_DIENST,
        False,
        prozesse=("monatsabschluss",),
        daten=(
            ("umsatzmeldung", Z.LESEN),
            ("kreditorenrechnungen", Z.LESEN),
            ("filialergebnisrechnung", Z.LESEN_SCHREIBEN),
        ),
        angelegt_vor=690,
        attestiert_vor=26,
    ),
    Werkzeug(
        "rechnungspruefung-app",
        "Rechnungsprüfung Freigabe",
        "Holt die sachliche Freigabe zu Kreditorenrechnungen ein.",
        "appsheet",
        "Formular",
        "steiner",
        "winkler",
        "finanzen",
        L.INTERAKTIV,
        I.PERSOENLICH,
        False,
        prozesse=("kreditorenpruefung",),
        daten=(("kreditorenrechnungen", Z.LESEN_SCHREIBEN), ("lieferscheine", Z.LESEN)),
        angelegt_vor=645,
        attestiert_vor=115,
    ),
    Werkzeug(
        "budgetkonsolidierung",
        "Budgetkonsolidierung",
        "Fasst die Bereichsplanungen zu einem Gesamtbudget zusammen.",
        "apps-script",
        "Kalkulation",
        "winkler",
        "steiner",
        "finanzen",
        L.INTERAKTIV,
        I.PERSOENLICH,
        False,
        prozesse=("budgetplanung-prozess",),
        daten=(("budgetplanung", Z.LESEN_SCHREIBEN), ("filialergebnisrechnung", Z.LESEN)),
        # Erklaerte undeklarierte Quellen: Schicht 2.
        attest=(False, True, True),
        angelegt_vor=465,
        attestiert_vor=145,
    ),
    Werkzeug(
        "filialergebnis-report",
        "Filialergebnis-Report",
        "Rechnet Erlöse und Kosten je Filiale zu einem Ergebnis.",
        "bigquery-gcs",
        "Auswertung",
        "winkler",
        "steiner",
        "finanzen",
        L.GEPLANT,
        I.BENANNTER_DIENST,
        False,
        prozesse=("filialergebnis",),
        daten=(
            ("filialergebnisrechnung", Z.LESEN),
            ("umsatzmeldung", Z.LESEN),
            ("energieverbrauch", Z.LESEN),
        ),
        angelegt_vor=445,
        attestiert_vor=68,
    ),
    Werkzeug(
        "steuermeldung-uebertrag",
        "Steuermeldung Übertragung",
        "Übermittelt die steuerlichen Kennzahlen an die Finanzverwaltung.",
        "python-kubernetes",
        "Schnittstelle",
        "steiner",
        "winkler",
        "finanzen",
        L.GETRIGGERT,
        I.BENANNTER_DIENST,
        False,
        prozesse=("steuerkennzahlen-meldung",),
        daten=(("steuerkennzahlen", Z.LESEN_SCHREIBEN),),
        ziele=("elster.finanzverwaltung.de",),
        angelegt_vor=485,
        attestiert_vor=54,
    ),
    Werkzeug(
        "anlagenzugang-mappe",
        "Anlagenzugangs-Mappe",
        "Übernimmt Zugänge aus dem Bauprojekt in die Anlagenbuchhaltung.",
        "apps-script",
        "Erfassung",
        "winkler",
        "steiner",
        "finanzen",
        L.INTERAKTIV,
        I.PERSOENLICH,
        False,
        prozesse=("anlagenzugaenge",),
        daten=(("anlagenbuchhaltung", Z.LESEN_SCHREIBEN), ("baufortschritt", Z.LESEN)),
        angelegt_vor=325,
        attestiert_vor=165,
    ),
    # --- Expansion und Immobilien -----------------------------------------
    Werkzeug(
        "standortmodell",
        "Standortmodell",
        "Schätzt das Umsatzpotenzial eines Standorts.",
        "bigquery-gcs",
        "Auswertung",
        "meixner",
        "haas",
        "expansion",
        L.INTERAKTIV,
        I.PERSOENLICH,
        False,
        prozesse=("standortbewertung",),
        daten=(
            ("standortdaten", Z.LESEN),
            ("standortprognosen", Z.LESEN_SCHREIBEN),
            ("abverkauf-filiale", Z.LESEN),
        ),
        angelegt_vor=515,
        attestiert_vor=125,
    ),
    Werkzeug(
        "mietvertragsfristen",
        "Mietvertragsfristen",
        "Überwacht Kündigungs- und Optionsfristen der Mietverträge.",
        "appsheet",
        "Erfassung",
        "meixner",
        "haas",
        "expansion",
        L.INTERAKTIV,
        I.PERSOENLICH,
        False,
        prozesse=("mietvertragsverwaltung",),
        daten=(("mietvertraege", Z.LESEN_SCHREIBEN), ("standortdaten", Z.LESEN)),
        angelegt_vor=475,
        attestiert_vor=136,
    ),
    Werkzeug(
        "bautenstands-app",
        "Bautenstands-App",
        "Erfasst den Bautenstand auf der Baustelle.",
        "appsheet",
        "Erfassung",
        "meixner",
        "haas",
        "expansion",
        L.INTERAKTIV,
        I.PERSOENLICH,
        False,
        prozesse=("bauprojektsteuerung",),
        daten=(("baufortschritt", Z.LESEN_SCHREIBEN),),
        angelegt_vor=395,
        attestiert_vor=195,
    ),
    Werkzeug(
        "energiemonitor",
        "Energiemonitor",
        "Vergleicht Verbrauchswerte je Filiale gegen den Vormonat.",
        "bigquery-gcs",
        "Auswertung",
        "meixner",
        "haas",
        "expansion",
        L.GEPLANT,
        I.BENANNTER_DIENST,
        False,
        prozesse=("energiemonitoring",),
        daten=(("energieverbrauch", Z.LESEN), ("sensordaten-kuehlung", Z.LESEN)),
        angelegt_vor=90,
        attestiert_vor=85,
    ),
    # --- Marketing und Kundenbindung --------------------------------------
    Werkzeug(
        "kundenkonto-pflege",
        "Kundenkontenpflege",
        "Pflegt Stammdaten und Einwilligungen der Kundenkarte.",
        "appsheet",
        "Erfassung",
        "kilian",
        "bergmann",
        "marketing",
        L.INTERAKTIV,
        I.PERSOENLICH,
        False,
        prozesse=("kundenkartenprogramm",),
        daten=(("kundenkartendaten", Z.LESEN_SCHREIBEN), ("kaufhistorie", Z.LESEN)),
        angelegt_vor=610,
        attestiert_vor=38,
    ),
    Werkzeug(
        "couponzuteilung",
        "Couponzuteilung",
        "Ordnet Coupons anhand der Kaufhistorie einzelnen Kunden zu.",
        "python-kubernetes",
        "Steuerung",
        "kilian",
        "bergmann",
        "marketing",
        L.GEPLANT,
        I.BENANNTER_DIENST,
        False,
        prozesse=("couponsteuerung",),
        daten=(
            ("kaufhistorie", Z.LESEN),
            ("coupon-einloesungen", Z.LESEN_SCHREIBEN),
            ("warenkorbanalysen", Z.LESEN),
        ),
        angelegt_vor=320,
        attestiert_vor=80,
    ),
    Werkzeug(
        "newsletterversand-strecke",
        "Newsletter-Versandstrecke",
        "Übergibt Verteiler und Inhalte an den Versanddienstleister.",
        "python-kubernetes",
        "Schnittstelle",
        "kilian",
        "bergmann",
        "marketing",
        L.GETRIGGERT,
        I.BENANNTER_DIENST,
        False,
        prozesse=("newsletterversand",),
        daten=(("newsletter-verteiler", Z.LESEN), ("handzettelpreise", Z.LESEN)),
        ziele=("versand.dienstleister.de",),
        angelegt_vor=430,
        attestiert_vor=96,
    ),
    Werkzeug(
        "werbemittelplanung-mappe",
        "Werbemittelplanungsmappe",
        "Ordnet Artikel den Werbeflächen des Handzettels zu.",
        "apps-script",
        "Kalkulation",
        "kilian",
        "bergmann",
        "marketing",
        L.INTERAKTIV,
        I.PERSOENLICH,
        False,
        prozesse=("werbemittelplanung-prozess",),
        daten=(("werbemittelplanung", Z.LESEN_SCHREIBEN), ("aktionsplanung-food", Z.LESEN)),
        angelegt_vor=355,
        attestiert_vor=142,
    ),
    Werkzeug(
        "reklamations-app",
        "Reklamations-App",
        "Nimmt Reklamationen im Servicecenter auf und verfolgt sie nach.",
        "appsheet",
        "Formular",
        "kilian",
        "bergmann",
        "marketing",
        L.INTERAKTIV,
        I.PERSOENLICH,
        False,
        prozesse=("reklamationsbearbeitung",),
        daten=(("reklamationen", Z.LESEN_SCHREIBEN), ("bondaten", Z.LESEN)),
        angelegt_vor=335,
        attestiert_vor=118,
    ),
    Werkzeug(
        "kampagnenexport",
        "Kampagnenexport Agentur",
        "Stellt Werbemitteldaten für die Agentur bereit.",
        "apps-script",
        "Schnittstelle",
        "kilian",
        "bergmann",
        "marketing",
        # Getriggert unter persoenlicher Identitaet und mit einem Ziel, das kein
        # Prozess erklaert hat: zwei Abweichungen in Schicht 1.
        L.GETRIGGERT,
        I.PERSOENLICH,
        False,
        prozesse=("werbemittelplanung-prozess",),
        daten=(("werbemittelplanung", Z.LESEN),),
        ziele=("agentur.dateiaustausch.de",),
        angelegt_vor=210,
        attestiert_vor=205,
    ),
    # --- Qualitätssicherung ------------------------------------------------
    Werkzeug(
        "probenplan-app",
        "Probenplan-App",
        "Steuert Probenziehung und Befundbewertung der Eigenmarken.",
        "appsheet",
        "Erfassung",
        "straub",
        "ziegler",
        "qs",
        L.INTERAKTIV,
        I.PERSOENLICH,
        False,
        prozesse=("eigenmarkenpruefung",),
        daten=(("laborbefunde", Z.LESEN_SCHREIBEN), ("lieferantenzertifikate", Z.LESEN)),
        angelegt_vor=655,
        attestiert_vor=44,
    ),
    Werkzeug(
        "rueckrufmelder",
        "Rückrufmeldung Behörde",
        "Übermittelt Rückrufmeldungen an das behördliche Meldeportal.",
        "python-kubernetes",
        "Schnittstelle",
        "straub",
        "ziegler",
        "qs",
        L.GETRIGGERT,
        I.BENANNTER_DIENST,
        False,
        prozesse=("rueckrufabwicklung",),
        daten=(("rueckrufmeldungen", Z.LESEN_SCHREIBEN), ("artikelstamm-food", Z.LESEN)),
        ziele=("meldeportal.lebensmittelwarnung.de",),
        angelegt_vor=630,
        attestiert_vor=22,
    ),
    Werkzeug(
        "hygieneprotokoll-app",
        "Hygieneprotokoll-App",
        "Führt die Hygienekontrolle in der Filiale.",
        "appsheet",
        "Formular",
        "straub",
        "ziegler",
        "qs",
        L.INTERAKTIV,
        I.PERSOENLICH,
        False,
        prozesse=("hygienekontrolle",),
        daten=(("hygieneprotokolle", Z.LESEN_SCHREIBEN), ("temperaturprotokolle", Z.LESEN)),
        angelegt_vor=540,
        attestiert_vor=128,
    ),
    Werkzeug(
        "unfallmeldung-app",
        "Unfallmeldungs-App",
        "Nimmt Unfallmeldungen auf und verfolgt die Maßnahmen.",
        "appsheet",
        "Formular",
        "straub",
        "ziegler",
        "qs",
        L.INTERAKTIV,
        I.PERSOENLICH,
        False,
        prozesse=("arbeitssicherheit",),
        daten=(("unfallmeldungen", Z.LESEN_SCHREIBEN), ("betriebsanweisungen", Z.LESEN)),
        angelegt_vor=470,
        attestiert_vor=158,
    ),
    Werkzeug(
        "auditmappe",
        "Auditmappe Lieferanten",
        "Dokumentiert Feststellungen und Nachverfolgung der Lieferantenaudits.",
        "apps-script",
        "Erfassung",
        "straub",
        "ziegler",
        "qs",
        L.INTERAKTIV,
        I.PERSOENLICH,
        False,
        prozesse=("lieferantenaudit",),
        daten=(("lieferantenaudits", Z.LESEN_SCHREIBEN), ("auditfeststellungen", Z.LESEN)),
        angelegt_vor=275,
        attestiert_vor=168,
    ),
    # --- IT und Digitalisierung -------------------------------------------
    Werkzeug(
        "schnittstellenwaechter",
        "Schnittstellenwächter",
        "Überwacht die Schnittstellen der Warenwirtschaft.",
        "python-kubernetes",
        "Steuerung",
        "hartwig",
        "pieper",
        "it",
        L.GEPLANT,
        I.BENANNTER_DIENST,
        False,
        prozesse=("schnittstellenbetrieb",),
        daten=(("systemprotokolle", Z.LESEN), ("schnittstellenverzeichnis", Z.LESEN)),
        angelegt_vor=700,
        attestiert_vor=18,
    ),
    Werkzeug(
        "berechtigungsauswertung",
        "Berechtigungsauswertung",
        "Stellt Rollen und Nutzer für das Review gegenüber.",
        "bigquery-gcs",
        "Auswertung",
        "pieper",
        "hartwig",
        "it",
        L.GEPLANT,
        I.BENANNTER_DIENST,
        False,
        prozesse=("berechtigungsreview",),
        daten=(("berechtigungsrollen", Z.LESEN_SCHREIBEN), ("personalstammdaten", Z.LESEN)),
        angelegt_vor=565,
        attestiert_vor=62,
    ),
    Werkzeug(
        "ladestrecke-warenwirtschaft",
        "Ladestrecke Warenwirtschaft",
        "Lädt Abverkauf, Bestand und Umsatz in die Auswertungsschicht.",
        "python-kubernetes",
        "Ladestrecke",
        "baumann",
        "hartwig",
        "it",
        L.GEPLANT,
        I.BENANNTER_DIENST,
        False,
        prozesse=("datenplattform",),
        daten=(
            ("abverkauf-filiale", Z.LESEN),
            ("bestand-filiale", Z.LESEN),
            ("umsatzmeldung", Z.LESEN),
            ("warenkorbanalysen", Z.LESEN_SCHREIBEN),
        ),
        angelegt_vor=585,
        attestiert_vor=33,
    ),
    Werkzeug(
        "datenqualitaets-pruefung",
        "Datenqualitätsprüfung",
        "Prüft die geladenen Daten auf Vollständigkeit und Plausibilität.",
        "bigquery-gcs",
        "Auswertung",
        "baumann",
        "hartwig",
        "it",
        L.GEPLANT,
        I.BENANNTER_DIENST,
        False,
        prozesse=("datenplattform",),
        daten=(("warenkorbanalysen", Z.LESEN),),
        angelegt_vor=520,
        attestiert_vor=72,
    ),
)

#: Was der Sync vorgefunden hat. Zwei Laeufe zu verschiedenen Zeitpunkten: der
#: aeltere liegt jenseits der Meldefrist und steht damit im Blockierungspfad.
VORGEFUNDENE_WERKZEUGE: tuple[tuple[int, str, str, str, str], ...] = (
    (
        210,
        "TOOL-EXT-01",
        "Bestellmengen-Korrekturmappe",
        "apps-script",
        "Korrigiert Bestellmengen vor der Übernahme in die Warenwirtschaft.",
    ),
    (
        210,
        "TOOL-EXT-02",
        "Aktionsauswertung Tabellenablage",
        "apps-script",
        "Wertet abgeschlossene Aktionen in einer Tabellenablage aus.",
    ),
    (
        210,
        "TOOL-EXT-03",
        "Personalkostenhochrechnung",
        "apps-script",
        "Rechnet Personalkosten je Filiale auf das Jahresende hoch.",
    ),
    (
        210,
        "TOOL-EXT-04",
        "Lieferantenanfragen-Formular",
        "appsheet",
        "Nimmt Rückfragen der Lieferanten zu Retouren auf.",
    ),
    (
        210,
        "TOOL-EXT-05",
        "Wareneingangsabgleich (Altbestand)",
        "python-kubernetes",
        "Gleicht Wareneingänge gegen die Avise ab.",
    ),
    (
        25,
        "TOOL-EXT-06",
        "Filialkennzahlen Rohauswertung",
        "apps-script",
        "Rohauswertung der Filialkennzahlen aus dem Kassensystem.",
    ),
    (
        25,
        "TOOL-EXT-07",
        "Schwundabgleich Regionalleitung",
        "apps-script",
        "Gleicht Schwundwerte mehrerer Filialen gegeneinander ab.",
    ),
)


def _kantentag(kontext: Kontext, eintrag: Werkzeug) -> int:
    """Der spaeteste Tag, an dem alle Enden einer Kante schon bestanden."""
    grenzen = [eintrag.angelegt_vor]
    if eintrag.attest is not None:
        grenzen.append(eintrag.attestiert_vor)
    grenzen.extend(kontext.angelegt[f"do:{d}"] for d, _art in eintrag.daten)
    grenzen.extend(kontext.angelegt[f"p:{p}"] for p in eintrag.prozesse)
    return max(6, min(grenzen) - 1)


def baue(kontext: Kontext) -> None:
    """Legt die Tool-Objekte an, attestiert sie und verknuepft ihre Kanten."""
    from app.bestand.organisation import QUELLE

    db = kontext.db
    for eintrag in WERKZEUGE:
        with kontext.aktion(eintrag.angelegt_vor, stunde=8 + (eintrag.angelegt_vor % 9)):
            tool = asset.lege_tool_an(
                db,
                kontext.wer(eintrag.owner),
                {
                    "name": eintrag.name,
                    "beschreibung": eintrag.beschreibung,
                    "technologie": eintrag.technologie,
                    "kategorie": eintrag.kategorie,
                    "technischer_owner_user_id": kontext.person(eintrag.owner).id,
                    "stellvertretung_user_id": kontext.person(eintrag.vertretung).id,
                    "organisationseinheit_id": kontext.einheit(eintrag.bereich).id,
                    "lauftyp": eintrag.lauftyp,
                    "ausfuehrungsidentitaet": eintrag.identitaet,
                    "statische_zugangsdaten": eintrag.statisch,
                    "externe_ziele": list(eintrag.ziele),
                    "letzte_aktivitaet_am": kontext.zeitpunkt(
                        eintrag.letzte_aktivitaet_vor, stunde=17
                    ),
                },
            )
        kontext.tools[eintrag.schluessel] = tool
        kontext.angelegt[f"t:{eintrag.schluessel}"] = eintrag.angelegt_vor

        if eintrag.attest is not None:
            entscheidung, mensch, quellen = eintrag.attest
            with kontext.aktion(eintrag.attestiert_vor, stunde=10):
                asset.attestiere(
                    db,
                    kontext.wer(eintrag.owner),
                    tool,
                    {
                        "attest_entscheidung_ueber_personen": entscheidung,
                        "attest_mensch_dazwischen": mensch,
                        "attest_undeklarierte_quellen": quellen,
                    },
                )

        # Die Kanten entstehen an einem Tag, an dem beide Enden schon da waren —
        # und nach der Attestierung, weil ohne sie keine Prozesskante zulaessig
        # ist (A.6).
        kanten_am = _kantentag(kontext, eintrag)
        for datenobjekt, zugriffsart in eintrag.daten:
            with kontext.aktion(kanten_am, stunde=11):
                asset.verknuepfe_tool_mit_datenobjekt(
                    db,
                    kontext.wer(eintrag.owner),
                    tool,
                    kontext.datenobjekt(datenobjekt),
                    zugriffsart,
                )

        for prozess in eintrag.prozesse:
            with kontext.aktion(kanten_am, stunde=13):
                asset.verknuepfe_tool_mit_prozess(
                    db, kontext.wer(eintrag.owner), tool, kontext.prozess(prozess)
                )

        if eintrag.stillgelegt:
            with kontext.aktion(eintrag.letzte_aktivitaet_vor - 1, stunde=16):
                asset.aendere_tool(db, kontext.wer(eintrag.owner), tool, {"status": "inaktiv"})

    for lauf in (210, 25):
        gefunden = [e for e in VORGEFUNDENE_WERKZEUGE if e[0] == lauf]
        if not gefunden:
            continue
        with kontext.aktion(lauf, stunde=3):
            importiere(
                db,
                ImportAnfrage(
                    quelle=QUELLE,
                    datensaetze=[
                        ImportDatensatz(
                            typ=ImportTyp.TOOL,
                            externe_id=externe_id,
                            name=name,
                            metadaten={"technologie": technologie, "beschreibung": beschreibung},
                        )
                        for _tag, externe_id, name, technologie, beschreibung in gefunden
                    ],
                ),
                akteur_user_id=kontext.person("lauterbach").id,
            )
