"""Fundament: Organisation, Prozess, Assets, Bewertung, Lenkung, Nachweis

Revision ID: 5804b5ba6002
Revises:
Create Date: 2026-09-01 12:55:42.316499

"""

from collections.abc import Sequence

import sqlalchemy as sa

import app.db
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "5804b5ba6002"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "fachbereiche",
        sa.Column("id", app.db.GUID(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("code", sa.String(length=32), nullable=False),
        sa.Column("quelle", sa.String(length=128), nullable=True),
        sa.Column("externe_id", sa.String(length=255), nullable=True),
        sa.Column(
            "erstellt_am",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column(
            "geaendert_am",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("quelle", "externe_id", name="uq_fachbereich_quelle"),
    )
    with op.batch_alter_table("fachbereiche", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_fachbereiche_code"), ["code"], unique=True)

    op.create_table(
        "konfiguration",
        sa.Column("id", app.db.GUID(), nullable=False),
        sa.Column("schluessel", sa.String(length=128), nullable=False),
        sa.Column("wert", sa.Text(), nullable=False),
        sa.Column("beschreibung", sa.Text(), nullable=False),
        sa.Column(
            "erstellt_am",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column(
            "geaendert_am",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("konfiguration", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_konfiguration_schluessel"), ["schluessel"], unique=True
        )

    op.create_table(
        "users",
        sa.Column("id", app.db.GUID(), nullable=False),
        sa.Column("subject", sa.String(length=255), nullable=False),
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("ist_aktiv", sa.Boolean(), nullable=False),
        sa.Column("fuehrungskraft_user_id", app.db.GUID(), nullable=True),
        sa.Column(
            "erstellt_am",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column(
            "geaendert_am",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["fuehrungskraft_user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_users_email"), ["email"], unique=True)
        batch_op.create_index(batch_op.f("ix_users_subject"), ["subject"], unique=True)

    op.create_table(
        "benachrichtigungen",
        sa.Column("id", app.db.GUID(), nullable=False),
        sa.Column("empfaenger_user_id", app.db.GUID(), nullable=False),
        sa.Column("anlass", sa.String(length=64), nullable=False),
        sa.Column("betreff", sa.String(length=255), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("entity_type", sa.String(length=64), nullable=True),
        sa.Column("entity_id", app.db.GUID(), nullable=True),
        sa.Column("gelesen", sa.Boolean(), nullable=False),
        sa.Column(
            "erstellt_am",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column(
            "geaendert_am",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["empfaenger_user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "change_log",
        sa.Column("cursor", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("id", app.db.GUID(), nullable=False),
        sa.Column("entity_type", sa.String(length=64), nullable=False),
        sa.Column("entity_id", app.db.GUID(), nullable=False),
        sa.Column("aktion", sa.String(length=16), nullable=False),
        sa.Column("vorher", sa.JSON(), nullable=True),
        sa.Column("nachher", sa.JSON(), nullable=True),
        sa.Column("akteur_user_id", app.db.GUID(), nullable=True),
        sa.Column("akteur_beschreibung", sa.String(length=255), nullable=False),
        sa.Column("zeitpunkt", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["akteur_user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("cursor"),
        sa.UniqueConstraint("id"),
    )
    with op.batch_alter_table("change_log", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_change_log_entity_id"), ["entity_id"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_change_log_entity_type"), ["entity_type"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_change_log_zeitpunkt"), ["zeitpunkt"], unique=False)

    op.create_table(
        "datenobjekte",
        sa.Column("id", app.db.GUID(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("beschreibung", sa.Text(), nullable=False),
        sa.Column("kategorie", sa.String(length=48), nullable=True),
        sa.Column("owner_user_id", app.db.GUID(), nullable=True),
        sa.Column("fachbereich_id", app.db.GUID(), nullable=True),
        sa.Column("herkunft", sa.String(length=16), nullable=False),
        sa.Column("quelle", sa.String(length=128), nullable=True),
        sa.Column("externe_id", sa.String(length=255), nullable=True),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("metadaten", sa.JSON(), nullable=False),
        sa.Column(
            "erstellt_am",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column(
            "geaendert_am",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["fachbereich_id"],
            ["fachbereiche.id"],
        ),
        sa.ForeignKeyConstraint(
            ["owner_user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("quelle", "externe_id", name="uq_datenobjekt_quelle"),
    )
    op.create_table(
        "organisationseinheiten",
        sa.Column("id", app.db.GUID(), nullable=False),
        sa.Column("fachbereich_id", app.db.GUID(), nullable=False),
        sa.Column("ebene", sa.String(length=8), nullable=False),
        sa.Column("land_code", sa.String(length=2), nullable=True),
        sa.Column("quelle", sa.String(length=128), nullable=True),
        sa.Column("externe_id", sa.String(length=255), nullable=True),
        sa.Column(
            "erstellt_am",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column(
            "geaendert_am",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["fachbereich_id"],
            ["fachbereiche.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("fachbereich_id", "ebene", "land_code", name="uq_orgeinheit"),
        sa.UniqueConstraint("quelle", "externe_id", name="uq_orgeinheit_quelle"),
    )
    op.create_table(
        "rollenzuweisungen",
        sa.Column("id", app.db.GUID(), nullable=False),
        sa.Column("user_id", app.db.GUID(), nullable=False),
        sa.Column("rolle", sa.String(length=32), nullable=False),
        sa.Column("scope_typ", sa.String(length=32), nullable=False),
        sa.Column("scope_id", app.db.GUID(), nullable=True),
        sa.Column(
            "erstellt_am",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column(
            "geaendert_am",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "rolle", "scope_typ", "scope_id", name="uq_rollenzuweisung"),
    )
    op.create_table(
        "prozessobjekte",
        sa.Column("id", app.db.GUID(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("owner_user_id", app.db.GUID(), nullable=False),
        sa.Column("stellvertretung_user_id", app.db.GUID(), nullable=False),
        sa.Column("prozessgeber_org_id", app.db.GUID(), nullable=False),
        sa.Column("supplier", sa.Text(), nullable=False),
        sa.Column("process_steps", sa.Text(), nullable=False),
        sa.Column("output", sa.Text(), nullable=False),
        sa.Column("customer", sa.String(length=24), nullable=False),
        sa.Column("ausfallfolge", sa.String(length=24), nullable=False),
        sa.Column("status", sa.String(length=24), nullable=False),
        sa.Column("reichweite", sa.String(length=24), nullable=True),
        sa.Column("kritikalitaet", sa.Integer(), nullable=False),
        sa.Column("mitbestimmung_flag", sa.Boolean(), nullable=False),
        sa.Column(
            "erstellt_am",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column(
            "geaendert_am",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["owner_user_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["prozessgeber_org_id"],
            ["organisationseinheiten.id"],
        ),
        sa.ForeignKeyConstraint(
            ["stellvertretung_user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "teams",
        sa.Column("id", app.db.GUID(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("quelle", sa.String(length=128), nullable=False),
        sa.Column("externe_id", sa.String(length=255), nullable=False),
        sa.Column("owner_hinweis", sa.String(length=320), nullable=True),
        sa.Column("organisationseinheit_id", app.db.GUID(), nullable=True),
        sa.Column(
            "erstellt_am",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column(
            "geaendert_am",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["organisationseinheit_id"],
            ["organisationseinheiten.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("quelle", "externe_id", name="uq_team_quelle"),
    )
    op.create_table(
        "tool_objekte",
        sa.Column("id", app.db.GUID(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("beschreibung", sa.Text(), nullable=False),
        sa.Column("technologie", sa.String(length=64), nullable=True),
        sa.Column("kategorie", sa.String(length=48), nullable=True),
        sa.Column("technischer_owner_user_id", app.db.GUID(), nullable=True),
        sa.Column("organisationseinheit_id", app.db.GUID(), nullable=True),
        sa.Column("herkunft", sa.String(length=16), nullable=False),
        sa.Column("quelle", sa.String(length=128), nullable=True),
        sa.Column("externe_id", sa.String(length=255), nullable=True),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("metadaten", sa.JSON(), nullable=False),
        sa.Column("letzte_aktivitaet_am", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "erstellt_am",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column(
            "geaendert_am",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["organisationseinheit_id"],
            ["organisationseinheiten.id"],
        ),
        sa.ForeignKeyConstraint(
            ["technischer_owner_user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("quelle", "externe_id", name="uq_tool_quelle"),
    )
    op.create_table(
        "alarme",
        sa.Column("id", app.db.GUID(), nullable=False),
        sa.Column("typ", sa.String(length=48), nullable=False),
        sa.Column("prozessobjekt_id", app.db.GUID(), nullable=True),
        sa.Column("beschreibung", sa.Text(), nullable=False),
        sa.Column("ausgeloest_von", app.db.GUID(), nullable=False),
        sa.Column("quittiert", sa.Boolean(), nullable=False),
        sa.Column(
            "erstellt_am",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column(
            "geaendert_am",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["ausgeloest_von"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["prozessobjekt_id"],
            ["prozessobjekte.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "bewertungen",
        sa.Column("id", app.db.GUID(), nullable=False),
        sa.Column("prozessobjekt_id", app.db.GUID(), nullable=False),
        sa.Column("ki_stufe", sa.Integer(), nullable=False),
        sa.Column("ds_stufe", sa.Integer(), nullable=False),
        sa.Column("mb_stufe", sa.Integer(), nullable=False),
        sa.Column("it_stufe", sa.Integer(), nullable=False),
        sa.Column("rg_stufe", sa.Integer(), nullable=False),
        sa.Column("ur_stufe", sa.Integer(), nullable=False),
        sa.Column("tier", sa.Integer(), nullable=False),
        sa.Column("gesperrt", sa.Boolean(), nullable=False),
        sa.Column("vollstaendig", sa.Boolean(), nullable=False),
        sa.Column("ausgeloeste_k_klassen", sa.JSON(), nullable=False),
        sa.Column("antworten", sa.JSON(), nullable=False),
        sa.Column("bewertet_von", app.db.GUID(), nullable=False),
        sa.Column("bewertet_am", sa.DateTime(timezone=True), nullable=False),
        sa.Column("gueltig_bis", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "erstellt_am",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column(
            "geaendert_am",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["bewertet_von"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["prozessobjekt_id"],
            ["prozessobjekte.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "compliance_zustaende",
        sa.Column("id", app.db.GUID(), nullable=False),
        sa.Column("tool_objekt_id", app.db.GUID(), nullable=False),
        sa.Column("farbe", sa.String(length=8), nullable=False),
        sa.Column("begruendung", sa.Text(), nullable=False),
        sa.Column("abweichung_art", sa.String(length=64), nullable=True),
        sa.Column("festgestellt_am", sa.DateTime(timezone=True), nullable=False),
        sa.Column("festgestellt_von", app.db.GUID(), nullable=True),
        sa.Column(
            "erstellt_am",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column(
            "geaendert_am",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["festgestellt_von"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tool_objekt_id"],
            ["tool_objekte.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "gate_vorgaenge",
        sa.Column("id", app.db.GUID(), nullable=False),
        sa.Column("prozessobjekt_id", app.db.GUID(), nullable=False),
        sa.Column("gate_typ", sa.String(length=4), nullable=False),
        sa.Column("ausloeser", sa.String(length=64), nullable=True),
        sa.Column("begruendung", sa.Text(), nullable=False),
        sa.Column("status", sa.String(length=24), nullable=False),
        sa.Column("eingereicht_von", app.db.GUID(), nullable=False),
        sa.Column("entschieden_von", app.db.GUID(), nullable=True),
        sa.Column("entscheidungskommentar", sa.Text(), nullable=False),
        sa.Column("entschieden_am", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "erstellt_am",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column(
            "geaendert_am",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["eingereicht_von"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["entschieden_von"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["prozessobjekt_id"],
            ["prozessobjekte.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "prozess_input_datenobjekte",
        sa.Column("prozessobjekt_id", app.db.GUID(), nullable=False),
        sa.Column("datenobjekt_id", app.db.GUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["datenobjekt_id"],
            ["datenobjekte.id"],
        ),
        sa.ForeignKeyConstraint(
            ["prozessobjekt_id"],
            ["prozessobjekte.id"],
        ),
        sa.PrimaryKeyConstraint("prozessobjekt_id", "datenobjekt_id"),
    )
    op.create_table(
        "prozess_kette",
        sa.Column("vorgaenger_id", app.db.GUID(), nullable=False),
        sa.Column("nachfolger_id", app.db.GUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["nachfolger_id"],
            ["prozessobjekte.id"],
        ),
        sa.ForeignKeyConstraint(
            ["vorgaenger_id"],
            ["prozessobjekte.id"],
        ),
        sa.PrimaryKeyConstraint("vorgaenger_id", "nachfolger_id"),
    )
    op.create_table(
        "prozess_output_datenobjekte",
        sa.Column("prozessobjekt_id", app.db.GUID(), nullable=False),
        sa.Column("datenobjekt_id", app.db.GUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["datenobjekt_id"],
            ["datenobjekte.id"],
        ),
        sa.ForeignKeyConstraint(
            ["prozessobjekt_id"],
            ["prozessobjekte.id"],
        ),
        sa.PrimaryKeyConstraint("prozessobjekt_id", "datenobjekt_id"),
    )
    op.create_table(
        "prozess_tool",
        sa.Column("prozessobjekt_id", app.db.GUID(), nullable=False),
        sa.Column("tool_objekt_id", app.db.GUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["prozessobjekt_id"],
            ["prozessobjekte.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tool_objekt_id"],
            ["tool_objekte.id"],
        ),
        sa.PrimaryKeyConstraint("prozessobjekt_id", "tool_objekt_id"),
    )
    op.create_table(
        "prozess_umsetzungen",
        sa.Column("id", app.db.GUID(), nullable=False),
        sa.Column("prozessobjekt_id", app.db.GUID(), nullable=False),
        sa.Column("land_org_id", app.db.GUID(), nullable=False),
        sa.Column("lokale_abweichung", sa.Text(), nullable=True),
        sa.Column(
            "erstellt_am",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column(
            "geaendert_am",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["land_org_id"],
            ["organisationseinheiten.id"],
        ),
        sa.ForeignKeyConstraint(
            ["prozessobjekt_id"],
            ["prozessobjekte.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("prozessobjekt_id", "land_org_id", name="uq_prozess_umsetzung"),
    )
    op.create_table(
        "selbstverpflichtungen",
        sa.Column("id", app.db.GUID(), nullable=False),
        sa.Column("typ", sa.String(length=32), nullable=False),
        sa.Column("prozessobjekt_id", app.db.GUID(), nullable=True),
        sa.Column("tool_objekt_id", app.db.GUID(), nullable=True),
        sa.Column("aussagen", sa.JSON(), nullable=False),
        sa.Column("vollstaendig", sa.Boolean(), nullable=False),
        sa.Column("abgegeben_von", app.db.GUID(), nullable=False),
        sa.Column("abgegeben_am", sa.DateTime(timezone=True), nullable=False),
        sa.Column("gueltig_bis", sa.DateTime(timezone=True), nullable=True),
        sa.Column("erinnerung_gesendet_am", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "erstellt_am",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column(
            "geaendert_am",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["abgegeben_von"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["prozessobjekt_id"],
            ["prozessobjekte.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tool_objekt_id"],
            ["tool_objekte.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "tool_datenobjekte",
        sa.Column("tool_objekt_id", app.db.GUID(), nullable=False),
        sa.Column("datenobjekt_id", app.db.GUID(), nullable=False),
        sa.Column("zugriffsart", sa.String(length=24), nullable=False),
        sa.ForeignKeyConstraint(
            ["datenobjekt_id"],
            ["datenobjekte.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tool_objekt_id"],
            ["tool_objekte.id"],
        ),
        sa.PrimaryKeyConstraint("tool_objekt_id", "datenobjekt_id"),
    )
    op.create_table(
        "lenkungsvorgaenge",
        sa.Column("id", app.db.GUID(), nullable=False),
        sa.Column("tool_objekt_id", app.db.GUID(), nullable=False),
        sa.Column("compliance_zustand_id", app.db.GUID(), nullable=True),
        sa.Column("eskalationsstufe", sa.Integer(), nullable=False),
        sa.Column("frist", sa.DateTime(timezone=True), nullable=False),
        sa.Column("zugewiesen_an", app.db.GUID(), nullable=True),
        sa.Column("status", sa.String(length=24), nullable=False),
        sa.Column("aufloesungsart", sa.String(length=32), nullable=True),
        sa.Column("aufloesung_bewertung_id", app.db.GUID(), nullable=True),
        sa.Column("aufgeloest_am", sa.DateTime(timezone=True), nullable=True),
        sa.Column("beschreibung", sa.Text(), nullable=False),
        sa.Column(
            "erstellt_am",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column(
            "geaendert_am",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["aufloesung_bewertung_id"],
            ["bewertungen.id"],
        ),
        sa.ForeignKeyConstraint(
            ["compliance_zustand_id"],
            ["compliance_zustaende.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tool_objekt_id"],
            ["tool_objekte.id"],
        ),
        sa.ForeignKeyConstraint(
            ["zugewiesen_an"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("lenkungsvorgaenge")
    op.drop_table("tool_datenobjekte")
    op.drop_table("selbstverpflichtungen")
    op.drop_table("prozess_umsetzungen")
    op.drop_table("prozess_tool")
    op.drop_table("prozess_output_datenobjekte")
    op.drop_table("prozess_kette")
    op.drop_table("prozess_input_datenobjekte")
    op.drop_table("gate_vorgaenge")
    op.drop_table("compliance_zustaende")
    op.drop_table("bewertungen")
    op.drop_table("alarme")
    op.drop_table("tool_objekte")
    op.drop_table("teams")
    op.drop_table("prozessobjekte")
    op.drop_table("rollenzuweisungen")
    op.drop_table("organisationseinheiten")
    op.drop_table("datenobjekte")
    with op.batch_alter_table("change_log", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_change_log_zeitpunkt"))
        batch_op.drop_index(batch_op.f("ix_change_log_entity_type"))
        batch_op.drop_index(batch_op.f("ix_change_log_entity_id"))

    op.drop_table("change_log")
    op.drop_table("benachrichtigungen")
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_users_subject"))
        batch_op.drop_index(batch_op.f("ix_users_email"))

    op.drop_table("users")
    with op.batch_alter_table("konfiguration", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_konfiguration_schluessel"))

    op.drop_table("konfiguration")
    with op.batch_alter_table("fachbereiche", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_fachbereiche_code"))

    op.drop_table("fachbereiche")
    # ### end Alembic commands ###
