"""Erklaerter Rahmen externer Ziele am Prozessobjekt

Revision ID: dbc373281ae4
Revises: 5804b5ba6002
Create Date: 2026-09-01 16:25:09.165751

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = 'dbc373281ae4'
down_revision: Union[str, Sequence[str], None] = '5804b5ba6002'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('prozessobjekte', schema=None) as batch_op:
        # Bestehende Zeilen bekommen die leere Liste; der Server-Default bleibt
        # stehen, damit auch ein direkter INSERT ohne dieses Feld gueltig ist.
        batch_op.add_column(
            sa.Column(
                'erlaubte_externe_ziele',
                sa.JSON(),
                nullable=False,
                server_default=sa.text("'[]'"),
            )
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('prozessobjekte', schema=None) as batch_op:
        batch_op.drop_column('erlaubte_externe_ziele')

    # ### end Alembic commands ###
